from _typeshed import Incomplete

class cursor:
    def callproc(self, procname, parameters: Incomplete | None = ...) -> None: ...
    def cast(self, oid, s) -> None: ...
    def close(self) -> None: ...
    def copy_expert(self, sql, file, size: int = ...) -> None: ...
    def copy_from(self, file, table, sep: Incomplete | None = ..., null: Incomplete | None = ..., size: int = ..., columns: Incomplete | None = ...) -> None: ...
    def copy_to(self, file, table, sep: Incomplete | None = ..., null: Incomplete | None = ..., columns: Incomplete | None = ...) -> None: ...
    def execute(self, query, vars: Incomplete | None = ...) -> None: ...
    def executemany(self, query, vars_list) -> None: ...
    def fetchall(self): ...
    def fetchmany(self, size: Incomplete | None = ...): ...
    def fetchone(self): ...
    def mogrify(self, query, vars: Incomplete | None = ...): ...
    def nextset(self) -> None: ...
    def scroll(self, value, mode: str = ...) -> None: ...
    def setinputsizes(self, sizes) -> None: ...
    def setoutputsize(self, size, column: Incomplete | None = ...) -> None: ...
    def __enter__(self, *args, **kwargs) -> None: ...
    def __exit__(self, *args, **kwargs) -> None: ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __iter__(self, *args, **kwargs): ...
    @staticmethod
    def __new__(*args, **kwargs) -> None: ...
    def __next__(self, *args, **kwargs) -> None: ...
    arraysize: Incomplete
    binary_types: Incomplete
    closed: Incomplete
    connection: Incomplete
    description: Incomplete
    itersize: Incomplete
    lastrowid: Incomplete
    name: Incomplete
    pgresult_ptr: Incomplete
    query: Incomplete
    rowcount: Incomplete
    rownumber: Incomplete
    row_factory: Incomplete
    scrollable: Incomplete
    statusmessage: Incomplete
    string_types: Incomplete
    typecaster: Incomplete
    tzinfo_factory: Incomplete
    withhold: Incomplete
