# coding: utf-8

"""
    Prompt.io APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AnalyticsInstantAppReportModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'timestamp_epoch': 'int',
        'instant_apps_outgoing': 'int',
        'instant_apps_opened': 'int',
        'instant_apps_created': 'int'
    }

    attribute_map = {
        'timestamp_epoch': 'timestampEpoch',
        'instant_apps_outgoing': 'instantAppsOutgoing',
        'instant_apps_opened': 'instantAppsOpened',
        'instant_apps_created': 'instantAppsCreated'
    }

    def __init__(self, timestamp_epoch=None, instant_apps_outgoing=None, instant_apps_opened=None, instant_apps_created=None):  # noqa: E501
        """AnalyticsInstantAppReportModel - a model defined in Swagger"""  # noqa: E501
        self._timestamp_epoch = None
        self._instant_apps_outgoing = None
        self._instant_apps_opened = None
        self._instant_apps_created = None
        self.discriminator = None
        if timestamp_epoch is not None:
            self.timestamp_epoch = timestamp_epoch
        if instant_apps_outgoing is not None:
            self.instant_apps_outgoing = instant_apps_outgoing
        if instant_apps_opened is not None:
            self.instant_apps_opened = instant_apps_opened
        if instant_apps_created is not None:
            self.instant_apps_created = instant_apps_created

    @property
    def timestamp_epoch(self):
        """Gets the timestamp_epoch of this AnalyticsInstantAppReportModel.  # noqa: E501

        The timestamp at the start of the default group-by window as a Unix timestamp.  # noqa: E501

        :return: The timestamp_epoch of this AnalyticsInstantAppReportModel.  # noqa: E501
        :rtype: int
        """
        return self._timestamp_epoch

    @timestamp_epoch.setter
    def timestamp_epoch(self, timestamp_epoch):
        """Sets the timestamp_epoch of this AnalyticsInstantAppReportModel.

        The timestamp at the start of the default group-by window as a Unix timestamp.  # noqa: E501

        :param timestamp_epoch: The timestamp_epoch of this AnalyticsInstantAppReportModel.  # noqa: E501
        :type: int
        """

        self._timestamp_epoch = timestamp_epoch

    @property
    def instant_apps_outgoing(self):
        """Gets the instant_apps_outgoing of this AnalyticsInstantAppReportModel.  # noqa: E501

        The number Instant Apps sent during the default group-by window.  # noqa: E501

        :return: The instant_apps_outgoing of this AnalyticsInstantAppReportModel.  # noqa: E501
        :rtype: int
        """
        return self._instant_apps_outgoing

    @instant_apps_outgoing.setter
    def instant_apps_outgoing(self, instant_apps_outgoing):
        """Sets the instant_apps_outgoing of this AnalyticsInstantAppReportModel.

        The number Instant Apps sent during the default group-by window.  # noqa: E501

        :param instant_apps_outgoing: The instant_apps_outgoing of this AnalyticsInstantAppReportModel.  # noqa: E501
        :type: int
        """

        self._instant_apps_outgoing = instant_apps_outgoing

    @property
    def instant_apps_opened(self):
        """Gets the instant_apps_opened of this AnalyticsInstantAppReportModel.  # noqa: E501

        The number Instant Apps opened during the default group-by window.  # noqa: E501

        :return: The instant_apps_opened of this AnalyticsInstantAppReportModel.  # noqa: E501
        :rtype: int
        """
        return self._instant_apps_opened

    @instant_apps_opened.setter
    def instant_apps_opened(self, instant_apps_opened):
        """Sets the instant_apps_opened of this AnalyticsInstantAppReportModel.

        The number Instant Apps opened during the default group-by window.  # noqa: E501

        :param instant_apps_opened: The instant_apps_opened of this AnalyticsInstantAppReportModel.  # noqa: E501
        :type: int
        """

        self._instant_apps_opened = instant_apps_opened

    @property
    def instant_apps_created(self):
        """Gets the instant_apps_created of this AnalyticsInstantAppReportModel.  # noqa: E501

        The number Instant Apps created during the default group-by window.  # noqa: E501

        :return: The instant_apps_created of this AnalyticsInstantAppReportModel.  # noqa: E501
        :rtype: int
        """
        return self._instant_apps_created

    @instant_apps_created.setter
    def instant_apps_created(self, instant_apps_created):
        """Sets the instant_apps_created of this AnalyticsInstantAppReportModel.

        The number Instant Apps created during the default group-by window.  # noqa: E501

        :param instant_apps_created: The instant_apps_created of this AnalyticsInstantAppReportModel.  # noqa: E501
        :type: int
        """

        self._instant_apps_created = instant_apps_created

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AnalyticsInstantAppReportModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnalyticsInstantAppReportModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
