# coding: utf-8

"""
    Prompt.io APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InstantAppDataModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'data': 'dict(str, str)',
        'id': 'int'
    }

    attribute_map = {
        'data': 'data',
        'id': 'id'
    }

    def __init__(self, data=None, id=None):  # noqa: E501
        """InstantAppDataModel - a model defined in Swagger"""  # noqa: E501
        self._data = None
        self._id = None
        self.discriminator = None
        if data is not None:
            self.data = data
        if id is not None:
            self.id = id

    @property
    def data(self):
        """Gets the data of this InstantAppDataModel.  # noqa: E501

        The values entered for each of the elements in the Instant App (on post may be a partial map)  # noqa: E501

        :return: The data of this InstantAppDataModel.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this InstantAppDataModel.

        The values entered for each of the elements in the Instant App (on post may be a partial map)  # noqa: E501

        :param data: The data of this InstantAppDataModel.  # noqa: E501
        :type: dict(str, str)
        """

        self._data = data

    @property
    def id(self):
        """Gets the id of this InstantAppDataModel.  # noqa: E501

        The Instant App numeric internal id.  # noqa: E501

        :return: The id of this InstantAppDataModel.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InstantAppDataModel.

        The Instant App numeric internal id.  # noqa: E501

        :param id: The id of this InstantAppDataModel.  # noqa: E501
        :type: int
        """

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InstantAppDataModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InstantAppDataModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
