"""
    IDX API

    Welcome to the IDX API.  # noqa: E501

    The version of the OpenAPI document: v2
    Contact: support@idx.us
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.order_get_dto_purchase_details import OrderGetDtoPurchaseDetails
globals()['OrderGetDtoPurchaseDetails'] = OrderGetDtoPurchaseDetails
from openapi_client.model.order_post_dto import OrderPostDto


class TestOrderPostDto(unittest.TestCase):
    """OrderPostDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderPostDto(self):
        """Test OrderPostDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrderPostDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
