"""
    IDX API

    Welcome to the IDX API.  # noqa: E501

    The version of the OpenAPI document: v2
    Contact: support@idx.us
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cyberscan_response_dto import CyberscanResponseDto


class TestCyberscanResponseDto(unittest.TestCase):
    """CyberscanResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCyberscanResponseDto(self):
        """Test CyberscanResponseDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CyberscanResponseDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
