"""
    IDX API

    Welcome to the IDX API.  # noqa: E501

    The version of the OpenAPI document: v2
    Contact: support@idx.us
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cyberscan_summary_get_dto_bank_account_inner import CyberscanSummaryGetDtoBankAccountInner
globals()['CyberscanSummaryGetDtoBankAccountInner'] = CyberscanSummaryGetDtoBankAccountInner
from openapi_client.model.cyberscan_summary_get_dto import CyberscanSummaryGetDto


class TestCyberscanSummaryGetDto(unittest.TestCase):
    """CyberscanSummaryGetDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCyberscanSummaryGetDto(self):
        """Test CyberscanSummaryGetDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CyberscanSummaryGetDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
