from _typeshed import Incomplete

class _out:
    dsp: str
    stdout: Incomplete
    def __init__(self) -> None: ...
    def write(self, txt) -> None: ...
    def flush(self) -> None: ...

class _base_send_class:
    def send(self, *args, **kwargs) -> None: ...

class NOT_SEND:
    rtn_code: Incomplete
    def __init__(self, RTN_CODE: Incomplete | None = ...) -> None: ...

def send(cls): ...
