#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['aiorate']

package_data = \
{'': ['*']}

extras_require = \
{'doc': ['sphinx']}

setup(name='aiorate',
      version='1.0.2',
      description='Loop frequency regulator for asyncio.',
      author=None,
      author_email='Stéphane Caron <stephane.caron@normalesup.org>',
      url=None,
      packages=packages,
      package_data=package_data,
      extras_require=extras_require,
      python_requires='>=3.7',
     )
