from _typeshed import Incomplete

class outlook:
    mail: Incomplete
    username: Incomplete
    passwd: Incomplete
    def __init__(self, username, passwd) -> None: ...
    def get_all_mail(self, limit: int = ...): ...
    def get_unread_mail(self, limit: int = ...): ...
    def phase(self, idx) -> dict: ...
    def __del__(self) -> None: ...
