
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-07T23:16:07+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1e4f32eb00b9729320a42e5200cd7539775a0cd3",
 "version": "0.2.53.post0.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
