# coding: utf-8

"""
    Prompt.io APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.pool_subchannel_model import PoolSubchannelModel  # noqa: E501
from swagger_client.rest import ApiException


class TestPoolSubchannelModel(unittest.TestCase):
    """PoolSubchannelModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPoolSubchannelModel(self):
        """Test PoolSubchannelModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.pool_subchannel_model.PoolSubchannelModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
