# coding: utf-8

"""
    Prompt.io APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.salesforce_integration_response_model import SalesforceIntegrationResponseModel  # noqa: E501
from swagger_client.rest import ApiException


class TestSalesforceIntegrationResponseModel(unittest.TestCase):
    """SalesforceIntegrationResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSalesforceIntegrationResponseModel(self):
        """Test SalesforceIntegrationResponseModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.salesforce_integration_response_model.SalesforceIntegrationResponseModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
