SENSOR_TYPE_TO_DATA_TYPE = {
    "A": 'boolean',
    "CV": 'boolean',
    "P": 'boolean',
    "AI": 'float',
    "AS": 'float',
    "C": 'float',
    "DI": 'float',
    "FI": 'float',
    "FIC": 'float',
    "FQ": 'float',
    "HIC": 'float',
    "II": 'float',
    "LI": 'float',
    "LIC": 'float',
    "LSH": 'float',
    "PHI": 'float',
    "PI": 'float',
    "PIC": 'float',
    "TI": 'float',
    "TIC": 'float',
    "VI": 'float',
    "WI": 'float',
    "WIC": 'float',
    "WQ": 'float',
    "ZI": 'float'
}
