
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-07T05:33:27+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "94e6e47cc890068b15c81432b49b87500516ed8b",
 "version": "1.17.1.post0.dev590"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
