"""
    Katalon TestOps API reference

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import testops_api
from testops_api.model.baseline_collection_resource import BaselineCollectionResource
from testops_api.model.k_eyes_execution_resource import KEyesExecutionResource
from testops_api.model.run_configuration_resource import RunConfigurationResource
globals()['BaselineCollectionResource'] = BaselineCollectionResource
globals()['KEyesExecutionResource'] = KEyesExecutionResource
globals()['RunConfigurationResource'] = RunConfigurationResource
from testops_api.model.baseline_collection_group_resource import BaselineCollectionGroupResource


class TestBaselineCollectionGroupResource(unittest.TestCase):
    """BaselineCollectionGroupResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBaselineCollectionGroupResource(self):
        """Test BaselineCollectionGroupResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BaselineCollectionGroupResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
