"""
    Katalon TestOps API reference

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import testops_api
from testops_api.model.baseline_resource import BaselineResource
from testops_api.model.checkpoint_content_resource import CheckpointContentResource
from testops_api.model.checkpoint_layout_resource import CheckpointLayoutResource
from testops_api.model.checkpoint_pixel_resource import CheckpointPixelResource
from testops_api.model.screenshot_resource import ScreenshotResource
from testops_api.model.upload_file_resource import UploadFileResource
globals()['BaselineResource'] = BaselineResource
globals()['CheckpointContentResource'] = CheckpointContentResource
globals()['CheckpointLayoutResource'] = CheckpointLayoutResource
globals()['CheckpointPixelResource'] = CheckpointPixelResource
globals()['ScreenshotResource'] = ScreenshotResource
globals()['UploadFileResource'] = UploadFileResource
from testops_api.model.checkpoint_resource import CheckpointResource


class TestCheckpointResource(unittest.TestCase):
    """CheckpointResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCheckpointResource(self):
        """Test CheckpointResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CheckpointResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
