"""
    Katalon TestOps API reference

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import testops_api
from testops_api.model.system_label_resource import SystemLabelResource
globals()['SystemLabelResource'] = SystemLabelResource
from testops_api.model.label_resource import LabelResource


class TestLabelResource(unittest.TestCase):
    """LabelResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLabelResource(self):
        """Test LabelResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LabelResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
