from .zfunct import rand
from .zfunct import slist
from .zfunct import splist
from .zfunct import rmlist
from .zfunct import fwrite
from .zfunct import fread
from .zfunct import curdir
from .zfunct import get_file_path
from .zfunct import get_file_name
from .zfunct import get_file_extension
from .zfunct import get_file_size
from .zfunct import get_file_date
from .zfunct import openf