def get_external_id_bytes(b: bytes, prefix: str) -> str: ...
def get_external_id_str(name: str, prefix: str) -> str: ...
def get_db_eid(database_name: str) -> str: ...
def get_table_eid(table_name: str) -> str: ...
def get_job_eid(job_name: str) -> str: ...
def get_req_eid() -> str: ...
def get_user_eid() -> str: ...
