
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-09T05:03:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3b90098f6f69944b41ada94fbfd504b97750d0d9",
 "version": "1.17.1.post0.dev613"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
