# coding: utf-8

"""
    Prompt.io APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class EventEndpointsApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def add_event_endpoint(self, **kwargs):  # noqa: E501
        """Creates an Event Endpoint  # noqa: E501

        _in snippets: platform.api.eventEndpoints.addEventEndpoint_  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_event_endpoint(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param EventEndpointModel body:
        :return: EventEndpointModel
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.add_event_endpoint_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.add_event_endpoint_with_http_info(**kwargs)  # noqa: E501
            return data

    def add_event_endpoint_with_http_info(self, **kwargs):  # noqa: E501
        """Creates an Event Endpoint  # noqa: E501

        _in snippets: platform.api.eventEndpoints.addEventEndpoint_  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_event_endpoint_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param EventEndpointModel body:
        :return: EventEndpointModel
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_event_endpoint" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['org_token']  # noqa: E501

        return self.api_client.call_api(
            '/event_endpoints', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='EventEndpointModel',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_event_endpoint(self, event_endpoint_id, **kwargs):  # noqa: E501
        """Deletes an Event Endpoint  # noqa: E501

        _in snippets: platform.api.eventEndpoints.deleteEventEndpoint_  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_event_endpoint(event_endpoint_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int event_endpoint_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_event_endpoint_with_http_info(event_endpoint_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_event_endpoint_with_http_info(event_endpoint_id, **kwargs)  # noqa: E501
            return data

    def delete_event_endpoint_with_http_info(self, event_endpoint_id, **kwargs):  # noqa: E501
        """Deletes an Event Endpoint  # noqa: E501

        _in snippets: platform.api.eventEndpoints.deleteEventEndpoint_  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_event_endpoint_with_http_info(event_endpoint_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int event_endpoint_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['event_endpoint_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_event_endpoint" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'event_endpoint_id' is set
        if ('event_endpoint_id' not in params or
                params['event_endpoint_id'] is None):
            raise ValueError("Missing the required parameter `event_endpoint_id` when calling `delete_event_endpoint`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'event_endpoint_id' in params:
            path_params['eventEndpointId'] = params['event_endpoint_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['org_token']  # noqa: E501

        return self.api_client.call_api(
            '/event_endpoints/{eventEndpointId}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_event_endpoint(self, event_endpoint_id, **kwargs):  # noqa: E501
        """Gets a specific Event Endpoint  # noqa: E501

        _in snippets: platform.api.eventEndpoints.getEventEndpoint_  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_event_endpoint(event_endpoint_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int event_endpoint_id: (required)
        :return: EventEndpointModel
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_event_endpoint_with_http_info(event_endpoint_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_event_endpoint_with_http_info(event_endpoint_id, **kwargs)  # noqa: E501
            return data

    def get_event_endpoint_with_http_info(self, event_endpoint_id, **kwargs):  # noqa: E501
        """Gets a specific Event Endpoint  # noqa: E501

        _in snippets: platform.api.eventEndpoints.getEventEndpoint_  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_event_endpoint_with_http_info(event_endpoint_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int event_endpoint_id: (required)
        :return: EventEndpointModel
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['event_endpoint_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_event_endpoint" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'event_endpoint_id' is set
        if ('event_endpoint_id' not in params or
                params['event_endpoint_id'] is None):
            raise ValueError("Missing the required parameter `event_endpoint_id` when calling `get_event_endpoint`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'event_endpoint_id' in params:
            path_params['eventEndpointId'] = params['event_endpoint_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['org_token']  # noqa: E501

        return self.api_client.call_api(
            '/event_endpoints/{eventEndpointId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='EventEndpointModel',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_event_endpoints(self, **kwargs):  # noqa: E501
        """Gets all Event Endpoints  # noqa: E501

        _in snippets: platform.api.eventEndpoints.getEventEndpoints_  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_event_endpoints(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int first:
        :param int max:
        :return: EventEndpointModelPage
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_event_endpoints_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_event_endpoints_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_event_endpoints_with_http_info(self, **kwargs):  # noqa: E501
        """Gets all Event Endpoints  # noqa: E501

        _in snippets: platform.api.eventEndpoints.getEventEndpoints_  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_event_endpoints_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int first:
        :param int max:
        :return: EventEndpointModelPage
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['first', 'max']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_event_endpoints" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'first' in params:
            query_params.append(('first', params['first']))  # noqa: E501
        if 'max' in params:
            query_params.append(('max', params['max']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['org_token']  # noqa: E501

        return self.api_client.call_api(
            '/event_endpoints', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='EventEndpointModelPage',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def reset_secret(self, event_endpoint_id, **kwargs):  # noqa: E501
        """Resets the secret for an Event Endpoint  # noqa: E501

        _in snippets: platform.api.eventEndpoints.resetSecret_  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.reset_secret(event_endpoint_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int event_endpoint_id: (required)
        :return: EventEndpointModel
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.reset_secret_with_http_info(event_endpoint_id, **kwargs)  # noqa: E501
        else:
            (data) = self.reset_secret_with_http_info(event_endpoint_id, **kwargs)  # noqa: E501
            return data

    def reset_secret_with_http_info(self, event_endpoint_id, **kwargs):  # noqa: E501
        """Resets the secret for an Event Endpoint  # noqa: E501

        _in snippets: platform.api.eventEndpoints.resetSecret_  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.reset_secret_with_http_info(event_endpoint_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int event_endpoint_id: (required)
        :return: EventEndpointModel
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['event_endpoint_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method reset_secret" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'event_endpoint_id' is set
        if ('event_endpoint_id' not in params or
                params['event_endpoint_id'] is None):
            raise ValueError("Missing the required parameter `event_endpoint_id` when calling `reset_secret`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'event_endpoint_id' in params:
            path_params['eventEndpointId'] = params['event_endpoint_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['org_token']  # noqa: E501

        return self.api_client.call_api(
            '/event_endpoints/{eventEndpointId}/reset_secret', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='EventEndpointModel',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_event_endpoint(self, event_endpoint_id, **kwargs):  # noqa: E501
        """Updates an Event Endpoint  # noqa: E501

        _in snippets: platform.api.eventEndpoints.updateEventEndpoint_  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_event_endpoint(event_endpoint_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int event_endpoint_id: (required)
        :param EventEndpointModel body:
        :return: EventEndpointModel
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_event_endpoint_with_http_info(event_endpoint_id, **kwargs)  # noqa: E501
        else:
            (data) = self.update_event_endpoint_with_http_info(event_endpoint_id, **kwargs)  # noqa: E501
            return data

    def update_event_endpoint_with_http_info(self, event_endpoint_id, **kwargs):  # noqa: E501
        """Updates an Event Endpoint  # noqa: E501

        _in snippets: platform.api.eventEndpoints.updateEventEndpoint_  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_event_endpoint_with_http_info(event_endpoint_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int event_endpoint_id: (required)
        :param EventEndpointModel body:
        :return: EventEndpointModel
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['event_endpoint_id', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_event_endpoint" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'event_endpoint_id' is set
        if ('event_endpoint_id' not in params or
                params['event_endpoint_id'] is None):
            raise ValueError("Missing the required parameter `event_endpoint_id` when calling `update_event_endpoint`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'event_endpoint_id' in params:
            path_params['eventEndpointId'] = params['event_endpoint_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['org_token']  # noqa: E501

        return self.api_client.call_api(
            '/event_endpoints/{eventEndpointId}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='EventEndpointModel',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
