

class PoeState: ...

class RsPoe:
    def setXmlFile(self, filename: str) -> bool: ...
    def getPortState(self, port: int) -> PoeState: ...
    def setPortState(self, port: int, state: PoeState) -> int: ...
    def getLastError(self) -> str: ...
    def version(self) -> str: ...