
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-09T20:32:27+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "98c641be04a41946fa690ff1434e9ca825cdbf8e",
 "version": "0.15.38"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
