
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-07T16:41:40+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a88c8844911bc6b49c6fb2b89bfc9e5fc5ca965b",
 "version": "1.6.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
