from _typeshed import Incomplete

class _dbBase:
    def __init__(self, dbModule, **dbInfo) -> None: ...
    def execute(self, query, vals: Incomplete | None = ..., *args, **kwargs): ...
    def close(self) -> None: ...
    def __del__(self) -> None: ...
