# This file automatically generated by
#    /Users/couchbase/jenkins/workspace/python/sdk/python-scripted-build-pipeline/py-client/./couchbase_version.py
# at
#    2022-12-08 08:43:00.748808
__version__ = '4.1.1rc1'