from _typeshed import Incomplete

class trueCaptcha:
    userId: Incomplete
    apiKey: Incomplete
    def __init__(self, userId, apiKey) -> None: ...
    def solver(self, captcha_image_url: str, session=..., case: str = ..., mode: str = ...) -> dict: ...
    def solverB64(self, imgB64Str: str, case: str = ..., mode: str = ...) -> dict: ...
    def usage(self) -> dict: ...
    def check(self) -> bool: ...
    @staticmethod
    def calc(exp: str): ...
