
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-07T22:28:43-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "09bd23b12e43c14fc837d1335c38c1449f4b5872",
 "version": "0.0.144"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
