
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-07T05:12:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f0fdf6144977eb913e74767035bb265bf1543176",
 "version": "1.17.1.post0.dev587"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
