RESOURCE_CREATE_STATUS_CODE = 'CREATE_RESOURCE_IN_PROGRESS'
RESOURCE_CREATE_STATUS_CODE_LIST = ['CREATE_CLUSTER_IN_PROGRESS', 'CREATE_NODEGROUP_IN_PROGRESS', 'CREATE_NAS_IN_PROGRESS', 'CREATE_K8S_RESOURCES_IN_PROGRESS', 'CREATE_KUBEFLOW_PIPELINE_RUN_IN_PROGRESS']
RESOURCE_FAIL_STATUS_CODE = 'FAILED_TO_CREATE_RESOURCES'
RESOURCE_FAIL_STATUS_CODE_LIST = ['FAILED_TO_CREATE_CLUSTER', 'FAILED_TO_CREATE_NODEGROUP', 'FAILED_TO_CREATE_NAS', 'FAILED_TO_CREATE_K8S_RESOURCES', 'FAILED_TO_CREATE_KUBEFLOW_PIPELINE_RUN']

def replace_status_code(status):
    if status in RESOURCE_CREATE_STATUS_CODE_LIST:
        return RESOURCE_CREATE_STATUS_CODE
    elif status in RESOURCE_FAIL_STATUS_CODE_LIST:
        return RESOURCE_FAIL_STATUS_CODE
    else:
        return status