
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-30T15:57:31-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "89cb6bde88bcb605085564aeebb33bd44c341c7a",
 "version": "12.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
