smaller_dict = [{"key": "genre_unsere_empfehlungen", "title": "Our recommendations", "conditions": {
    "tld": ["de", "com", "eu", "net", "org", "info", "online", "store", "tech", "site", "page", "club", "website", "it",
            "cloud", "shop", "xyz", "one", "gmbh", "app", "email", "space", "blog", "rocks", "design", "immo",
            "immobilien", "jetzt", "kaufen", "center", "bayern", "hamburg", "nrw", "koeln", "ruhr", "top", "cologne",
            "world", "tips", "digital", "bio", "click", "expert", "work", "solutions", "global", "international",
            "services", "news", "events", "reisen", "art", "academy", "systems", "onl", "life", "wiki", "media",
            "consulting", "guru", "team", "group", "support", "company", "versicherung", "bike", "software", "live",
            "photography", "training", "today", "network", "agency", "business", "technology", "marketing", "link",
            "party", "land", "city", "zone", "london", "photos", "dental", "management", "schule", "fun", "love",
            "earth", "haus", "fit", "photo", "coach", "bar", "bid", "plus", "fashion", "discount", "help", "sale"]},
                "type": "primary"}, {"key": "genre_staedte_regionen", "title": "Cities & Regions", "conditions": {
    "tld": ["berlin", "bayern", "hamburg", "nrw", "koeln", "cologne", "wien", "zuerich", "swiss", "amsterdam", "osaka",
            "london", "istanbul", "scot", "indians", "land", "vegas", "quebec", "miami", "irish", "here", "kyoto",
            "dubai", "country", "arab", "tokyo", "capetown", "yokohama", "tour", "eus", "cymru", "krd", "helsinki",
            "gent", "durban", "corsica", "boston", "okinawa", "world", "cern", "brussels", "rio", "barcelona",
            "tirol"]}, "type": "other"}, {"key": "genre_lifestyle", "title": "Lifestyle", "conditions": {
    "tld": ["party", "club", "blog", "vip", "fun", "site", "beauty", "living", "online", "design", "store", "guru",
            "date", "today", "racing", "one", "nyc", "services", "art"]}, "type": "other"},
               {"key": "genre_audio_video", "title": "Audio & Video", "conditions": {
                   "tld": ["stream", "live", "studio", "video", "film", "music", "website", "download", "cam", "vision",
                           "party",
                           "services", "guru", "tube", "technology", "download", "art", "beats", "band", "rocks", "fun",
                           "gallery",
                           "gallery", "hiphop", "tickets", "theatre", "tour", "tube", "watch", "show", "play", "tunes",
                           "audible",
                           "music"]}, "type": "other"},
               {"key": "genre_media_musik", "title": "Media & Music", "conditions": {
                   "tld": ["band", "rocks", "club", "live", "guitars", "beats", "digital", "events", "film", "booking",
                           "party",
                           "audible", "download", "joy", "channel", "theater", "studio", "stream", "photography",
                           "graphics", "energy",
                           "community", "box", "audio", "best", "song", "tunes", "movie", "camera"]}, "type": "other"},
               {"key": "genre_technik_it", "title": "Technology & IT", "conditions": {
                   "tld": ["hosting", "technology", "codes", "email", "io", "ki", "ai", "dev", "digital", "expert",
                           "news", "radio",
                           "site", "audible", "video", "center", "web", "how", "solutions", "mobile", "computer", "zip",
                           "business",
                           "office", "science", "network", "link", "domains", "channel", "android", "download", "codes",
                           "engineer",
                           "ing", "drive", "save", "webs", "host", "forum", "mail", "storage", "foo", "exchange",
                           "call", "bot",
                           "app", "chat"]}, "type": "other"},
               {"key": "genre_shopping", "title": "Shopping", "conditions": {
                   "tld": ["shop", "kaufen", "discount", "promo", "fashion", "buy", "boots", "deal", "dealer",
                           "flowers", "food",
                           "shoes", "auto", "moda", "coupons", "markets", "car", "cars", "gratis"]}, "type": "other"},
               {"key": "genre_business", "title": "Business", "conditions": {
                   "tld": ["business", "ceo", "gmbh", "agency", "enterprises", "apartments", "app", "attorney",
                           "autoinsurance",
                           "blackfriday", "boots", "abogado", "buy", "cash", "analytics", "clothing", "consulting",
                           "credit", "deals",
                           "dental", "design", "discount", "engineering", "enterprises", "finance", "food",
                           "foundation", "fund",
                           "gmbh", "gold", "grocery", "holdings", "immo", "immobilien", "industries", "kaufen",
                           "limited", "ltd",
                           "luxury", "market", "partners", "services", "shop", "shopping", "trade", "trading",
                           "versicherung",
                           "vision", "restaurant", "translations", "tickets", "review", "inc", "catering", "capital",
                           "construction",
                           "sarl", "ventures", "insure", "careers", "cal contractors"]}, "type": "other"},
               {"key": "genre_fitness_gesundheit", "title": "Fitness & Health", "conditions": {
                   "tld": ["fit", "team", "club", "courses", "studio", "yoga", "med", "blog", "club", "clothing",
                           "expert", "help",
                           "kids", "food", "news", "shopping", "sport", "team", "cancerresearch", "active", "center",
                           "dental",
                           "travelersinsurance", "you", "winners", "top", "today", "studio", "spa", "science",
                           "organic", "kitchen",
                           "health", "health", "eat", "dance", "community", "beauty", "supplies", "surgery", "limited",
                           "best", "eus",
                           "observer", "tennis", "run", "doctor", "clinic", "care", "basketball", "bargains", "heart",
                           "retirement"]},
                "type": "other"}, {"key": "genre_finanzen", "title": "Finance", "conditions": {
        "tld": ["blog", "office", "club", "autoinsurance", "app", "banque", "business", "buy", "discount", "deal",
                "dealer",
                "expert", "got", "ads", "immo", "legal", "ltd", "one", "pay", "sale", "scholarships", "management",
                "deals",
                "finance", "rich", "channel", "zone", "win", "trading", "trade", "today", "top", "training", "citic",
                "safe", "market", "llp", "holdings", "markets", "fund", "loan", "loans", "rent", "agency", "supply",
                "report", "rest", "cash", "financial", "creditcard", "tax", "property", "accountant", "courses",
                "investments", "exchange", "contractors"]}, "type": "other"},
               {"key": "genre_bildung_politik", "title": "Education & Policy", "conditions": {
                   "tld": ["university", "school", "schule", "college", "academy", "education", "institute", "democrat",
                           "university",
                           "voting", "vote", "republican", "read", "school", "author", "career", "services", "press",
                           "education",
                           "docs", "academy", "camp", "retirement", "ing", "courses", "college", "shiksha", "voting",
                           "vote",
                           "republican", "democrat"]}, "type": "other"},
               {"key": "genre_persoenliches", "title": "Personal",
                "conditions": {
                    "tld": ["wedding", "family", "bio", "singles", "house",
                            "lol", "baby", "pet", "pets", "book", "circle",
                            "music", "party", "pics", "reise", "author",
                            "site", "website", "bike", "kid", "you", "wed",
                            "training", "smile", "rocks", "photo",
                            "lifestyle", "football", "faith", "dad",
                            "coach", "man", "limited", "beer", "moi",
                            "hangout", "hiv", "wow", "realty", "leclerc",
                            "fail", "lgbt"]}, "type": "other"},
               {"key": "genre_kunst_kultur", "title": "Art & Culture", "conditions": {
                   "tld": ["photos", "vision", "design", "club", "art", "arte", "actor", "music", "guru", "joy",
                           "photo", "guitars",
                           "mov", "meme", "diy", "cool"]}, "type": "other"},
               {"key": "genre_sport_hobbys", "title": "Sports & Hobbies", "conditions": {
                   "tld": ["team", "golf", "band", "club", "bike", "poker", "garden", "auto", "pet", "pets", "book",
                           "golf", "blog",
                           "one", "pics", "author", "ski", "website", "wiki", "active", "bike", "channel", "zone",
                           "watch",
                           "training", "talk", "yachts", "style", "rodeo", "poker", "photos", "horse", "graphics",
                           "games", "futbol",
                           "final", "fans", "dog", "cricket", "baseball", "autos", "audio", "motorcycles", "cars",
                           "fitness", "surf",
                           "hockey", "cooking", "play", "sex", "fishing", "soccer", "rugby", "racing", "ninja", "fish",
                           "bingo",
                           "frogans", "fan", "reit", "clothing", "lotto", "pictures"]}, "type": "other"},
               {"key": "genre_essen_trinken", "title": "Food & Drink", "conditions": {
                   "tld": ["pizza", "limo", "recipes", "kitchen", "diet", "buy", "dish", "fit", "shop", "cafe", "like",
                           "bio", "diy",
                           "kaufen", "store", "services", "soy", "organic", "club", "orange", "energy", "food", "coach",
                           "box",
                           "arab", "vin", "ryukyu", "ice", "courses", "bar", "kiwi", "kosher", "cuisinella", "blog",
                           "grocery",
                           "menu", "pub", "halal"]}, "type": "other"},
               {"key": "genre_produkte", "title": "Products", "conditions": {
                   "tld": ["jewelry", "clothing", "shop", "tires", "kaufen", "cheap", "office", "email", "game", "app",
                           "art", "pets",
                           "boots", "glass", "flowers", "free", "music", "reise", "sport", "cafe", "software", "vodka",
                           "yachts",
                           "dish", "equipment", "repair", "boats", "car", "properties", "blackfriday", "buy"]},
                "type": "other"},
               {"key": "genre_nachrichten", "title": "News", "conditions": {
                   "tld": ["news", "email", "report", "chat", "radio", "express", "blog", "one", "pics", "digital",
                           "site", "website",
                           "room", "mobile", "you", "app", "studio", "press", "fyi", "direct", "box", "world", "talk",
                           "xyz", "best",
                           "exposed"]}, "type": "other"}, {"key": "genre_services", "title": "Services", "conditions": {
        "tld": ["repair", "law", "support", "help", "florist", "call", "boots", "digital", "express", "clothing", "med",
                "security", "software", "room", "tires", "engineering", "tax"]}, "type": "other"},
               {"key": "genre_reisen", "title": "Travel", "conditions": {
                   "tld": ["flights", "voyage", "holiday", "world", "vacations", "amsterdam", "bayern", "berlin",
                           "hotel", "earth",
                           "express", "scot", "istanbul", "london", "map", "paris", "roma", "saarland", "tour", "tours",
                           "wien",
                           "hotels", "thai", "cologne", "place", "kyoto", "club", "dubai", "country", "broadway",
                           "arab", "tokyo",
                           "taipei", "holiday", "booking", "nagoya", "okinawa", "cymru", "fly", "nyc", "rio", "weather",
                           "africa",
                           "melbourne", "hoteles", "guide", "cruises", "blog", "travelers", "vlaanderen", "joburg",
                           "wales",
                           "viajes"]}, "type": "other"},
               {"key": "genre_organisationen", "title": "Organizations", "conditions": {
                   "tld": ["social", "institute", "club", "help", "vision", "gmbh", "group", "school", "site", "team",
                           "website",
                           "wiki", "active", "trust", "earth", "blog", "press", "office", "corp", "academy", "world",
                           "circle",
                           "lgbt"]}, "type": "other"},
               {"key": "genre_immobilien", "title": "Real estate", "conditions": {
                   "tld": ["house", "sale", "kaufen", "villas", "rentals", "realestate", "express", "expert", "gmbh",
                           "hamburg",
                           "help", "koeln", "madrid", "one", "news", "paris", "club", "wien", "budapest", "hotels",
                           "booking", "watch",
                           "sydney", "place", "luxe", "office", "markets", "bid", "auction", "build", "lease", "best",
                           "town", "spot",
                           "blog", "earth", "maison", "homes", "home", "realtor", "claims", "casa", "mortgage"]},
                "type": "other"},
               {"key": "genre_industrie_branchen", "title": "Industry & Industries", "conditions": {
                   "tld": ["technology", "trading", "science", "shop", "industries", "clothing", "blog", "boots",
                           "office", "game",
                           "icu", "banque", "digital", "eco", "financialaid", "immo", "immobilien", "legal", "money",
                           "one",
                           "apartments", "pizza", "author", "security", "versicherung", "wine", "deals", "carinsurance",
                           "design",
                           "cam", "career", "dental", "farmers", "kid", "store", "study", "room", "mobile", "support",
                           "taxi",
                           "medical", "florist", "tattoo", "solar", "salon", "hotel", "physio", "photo", "moda",
                           "repair", "hospital",
                           "healthcare", "furniture", "abogado", "bet", "moto", "autos", "lifeinsurance", "motorcycles",
                           "academy",
                           "company", "computer", "loans", "rent", "estate", "engineer", "vacations", "cleaning",
                           "tires",
                           "engineering", "cash", "credit", "creditcard", "lawyer", "cruise", "gree"]},
                "type": "other"},
               {"key": "genre_technologie", "title": "Technology", "conditions": {
                   "tld": ["solutions", "builders", "auto", "app", "digital", "business", "film", "antivirus", "phone",
                           "radio",
                           "secure", "video", "data", "office", "webcam", "game", "network"]}, "type": "other"},
               {"key": "genre_marketing", "title": "Marketing", "conditions": {
                   "tld": ["marketing", "consulting", "management", "business", "expert", "blog", "digital", "discount",
                           "express",
                           "events", "app", "gmbh", "site", "observer", "jetzt", "deals", "career", "guru", "win",
                           "vision", "top",
                           "training", "today", "talk", "rocks", "new", "market", "fast", "enterprises", "coupon",
                           "cheap", "buzz",
                           "bot", "company", "whoswho", "courses", "productions", "report", "tools", "wtf"]},
                "type": "other"},
               {"key": "genre_handel_handwerk", "title": "Trade & Craft", "conditions": {
                   "tld": ["productions", "repair", "services", "expert", "work", "shop", "florist", "glass",
                           "accountant", "tires",
                           "clothing", "buy", "cool", "deal", "express", "observer", "free", "help", "ads",
                           "immobilien", "kids",
                           "ceo", "sale", "shopping", "site", "versicherung", "team", "website", "carinsurance",
                           "center", "kaufen",
                           "courses", "systems", "salon", "institute", "corp", "boutique", "motorcycles", "company",
                           "car", "farm",
                           "engineer", "ing", "gifts", "qpon", "reviews", "gift", "forsale", "feedback", "compare",
                           "contact",
                           "works", "cards", "gbiz", "bargains", "toys", "coffee", "coffee careers", "sarl", "delivery",
                           "parts",
                           "hair", "tienda", "cab", "associates"]}, "type": "other"},
               {"key": "genre_erwachsene", "title": "Adult",
                "conditions": {
                    "tld": ["porn", "xxx", "sexy", "adult",
                            "hot", "free", "fun", "film",
                            "live", "gay", "dating", "joy",
                            "singles", "bar", "webcam",
                            "sucks", "rodeo", "men", "date",
                            "express", "diamonds", "dad",
                            "bet", "page", "directory", "beer",
                            "club", "mom", "casino", "chat",
                            "site", "poker", "lotto"]},
                "type": "other"},
               {"key": "genre_profis", "title": "Professionals", "conditions": {
                   "tld": ["repair", "engineer", "expert", "ceo", "best", "management", "author", "security", "prof",
                           "career",
                           "builders", "physio", "dentist", "plumbing", "consulting", "auto", "help", "fit", "ing",
                           "accountants",
                           "vip", "fire"]}, "type": "other"}, {"key": "genre_farben", "title": "Colors", "conditions": {
        "tld": ["orange", "red", "pink", "green", "gold", "blue", "black"]}, "type": "other"},
               {"key": "genre_sonstiges", "title": "Miscellaneous", "conditions": {
                   "tld": ["gop", "mma", "llc", "wtc", "rsvp", "mormon", "lat", "lds", "ooo", "kim", "wang", "zero",
                           "vet", "rehab",
                           "ltda", "protection", "now", "mutual", "mls", "latino", "jot", "ist", "ira", "frl", "degree",
                           "day", "gal",
                           "cal", "archi", "are", "alsace", "doha", "dot", "ink", "uno", "lighting", "condos", "gripe",
                           "gives",
                           "desi", "moe", "bzh", "phd", "shia", "crs", "dnp", "emerck", "esq", "gle", "globo", "post",
                           "voto", "mba",
                           "srl", "juegos", "bcn", "boo"]}, "type": "other"},
               {"key": "genre_religion", "title": "Religion",
                "conditions": {
                    "tld": ["bible", "memorial", "rip", "islam",
                            "ismaili", "church", "christmas"]},
                "type": "other"},
               {"key": "genre_valentinstag", "title": "Valentine's Day",
                "conditions": {
                    "tld": ["love", "best", "gift", "baby", "wedding", "partners", "sexy", "gold", "flowers"]},
                "type": "other"},
               {"key": "category_international", "title": "International", "conditions": {"category": [7]},
                "type": "international"},
               {"key": "category_europe", "title": "Europe", "conditions": {"category": [1]}, "type": "continent"},
               {"key": "category_asia", "title": "Asia", "conditions": {"category": [5]}, "type": "continent"},
               {"key": "category_america", "title": "America", "conditions": {"category": [2, 3]}, "type": "continent"},
               {"key": "category_africa", "title": "Africa", "conditions": {"category": [4]}, "type": "continent"},
               {"key": "category_australia", "title": "Australia", "conditions": {"category": [6]},
                "type": "continent"}]


if __name__ == '__main__':
    print(len(smaller_dict))
    main_arr = []
    for i in range(len(smaller_dict)):
        print(i)
        main_arr.extend(smaller_dict[i]["conditions"]["tld"])
        print(smaller_dict[i]["conditions"]["tld"])
    print(main_arr)
