from ._symbol import Symbol
from typing import Any

class Container:
    def register(self, key: Symbol, instance: Any) -> None: ...
    def get(self, key: Symbol) -> Any: ...
    def clear(self) -> None: ...
    def remove(self, key: Symbol) -> None: ...

class Symbol:
    def __init__(self, key: str) -> None: ...

container: Container
