# coding: utf-8

"""
    Prompt.io APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.conversation_model_page import ConversationModelPage  # noqa: E501
from swagger_client.rest import ApiException


class TestConversationModelPage(unittest.TestCase):
    """ConversationModelPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConversationModelPage(self):
        """Test ConversationModelPage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.conversation_model_page.ConversationModelPage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
