
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-09T15:43:14-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "8b1667f1165c78cfc8979ac4afb4e5400ffc0292",
 "version": "0.0.147"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
