from typing import Dict

class OutputMode: ...

class RsDio:
    def setXmlFile(self, filename: str, debug: bool=False) -> None: ...
    def setOutputMode(self, dio: int, mode: OutputMode) -> None: ...
    def digitalRead(self, dio: int, pin: int) -> bool: ...
    def digitalWrite(self, dio: int, pin: int, state: bool) -> None: ...
    def readAll(self, dio: int) -> Dict[int, bool]: ...
    def getLastError(self) -> str: ...
    def version(self) -> str: ...
