# This file automatically generated by
#    /home/couchbase/jenkins/workspace/python/sdk/python-scripted-build-pipeline/py-client/couchbase_version.py
# at
#    2022-12-08 16:16:00.157878
__version__ = '4.1.1rc1'