from useckit.models.cnn import Classifier_CNN
from useckit.models.encoder import Classifier_ENCODER
from useckit.models.fcn import Classifier_FCN
from useckit.models.inception import Classifier_INCEPTION
from useckit.models.mcdcnn import Classifier_MCDCNN
from useckit.models.mcnn import Classifier_MCNN
from useckit.models.mlp import Classifier_MLP
from useckit.models.resnet import Classifier_RESNET
from useckit.models.tlenet import Classifier_TLENET
from useckit.models.twiesn import Classifier_TWIESN
