
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-07T19:04:09+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "d03e0d32b6571b0f1909bdd895400523d7c70f3a",
 "version": "v3.2.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
