# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scann/proto/centers.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from scann.data_format import features_pb2 as scann_dot_data__format_dot_features__pb2
from scann.proto import hash_pb2 as scann_dot_proto_dot_hash__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='scann/proto/centers.proto',
  package='research_scann',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x19scann/proto/centers.proto\x12\x0eresearch_scann\x1a scann/data_format/features.proto\x1a\x16scann/proto/hash.proto\"\xb7\x01\n\x16\x43\x65ntersForAllSubspaces\x12<\n\x10subspace_centers\x18\x01 \x03(\x0b\x32\".research_scann.CentersForSubspace\x12_\n\x13quantization_scheme\x18\x02 \x01(\x0e\x32\x39.research_scann.AsymmetricHasherConfig.QuantizationScheme:\x07PRODUCT\"J\n\x12\x43\x65ntersForSubspace\x12\x34\n\x06\x63\x65nter\x18\x01 \x03(\x0b\x32$.research_scann.GenericFeatureVector')
  ,
  dependencies=[scann_dot_data__format_dot_features__pb2.DESCRIPTOR,scann_dot_proto_dot_hash__pb2.DESCRIPTOR,])




_CENTERSFORALLSUBSPACES = _descriptor.Descriptor(
  name='CentersForAllSubspaces',
  full_name='research_scann.CentersForAllSubspaces',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subspace_centers', full_name='research_scann.CentersForAllSubspaces.subspace_centers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantization_scheme', full_name='research_scann.CentersForAllSubspaces.quantization_scheme', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=287,
)


_CENTERSFORSUBSPACE = _descriptor.Descriptor(
  name='CentersForSubspace',
  full_name='research_scann.CentersForSubspace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='center', full_name='research_scann.CentersForSubspace.center', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=363,
)

_CENTERSFORALLSUBSPACES.fields_by_name['subspace_centers'].message_type = _CENTERSFORSUBSPACE
_CENTERSFORALLSUBSPACES.fields_by_name['quantization_scheme'].enum_type = scann_dot_proto_dot_hash__pb2._ASYMMETRICHASHERCONFIG_QUANTIZATIONSCHEME
_CENTERSFORSUBSPACE.fields_by_name['center'].message_type = scann_dot_data__format_dot_features__pb2._GENERICFEATUREVECTOR
DESCRIPTOR.message_types_by_name['CentersForAllSubspaces'] = _CENTERSFORALLSUBSPACES
DESCRIPTOR.message_types_by_name['CentersForSubspace'] = _CENTERSFORSUBSPACE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CentersForAllSubspaces = _reflection.GeneratedProtocolMessageType('CentersForAllSubspaces', (_message.Message,), {
  'DESCRIPTOR' : _CENTERSFORALLSUBSPACES,
  '__module__' : 'scann.proto.centers_pb2'
  # @@protoc_insertion_point(class_scope:research_scann.CentersForAllSubspaces)
  })
_sym_db.RegisterMessage(CentersForAllSubspaces)

CentersForSubspace = _reflection.GeneratedProtocolMessageType('CentersForSubspace', (_message.Message,), {
  'DESCRIPTOR' : _CENTERSFORSUBSPACE,
  '__module__' : 'scann.proto.centers_pb2'
  # @@protoc_insertion_point(class_scope:research_scann.CentersForSubspace)
  })
_sym_db.RegisterMessage(CentersForSubspace)


# @@protoc_insertion_point(module_scope)
