
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-06T13:10:51+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4c1362e5bb40398c8c641c9c50c8d053afd45a4e",
 "version": "2807"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
