# coding: utf-8

"""
    Prompt.io APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MapIconModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'api_id': 'str',
        'is_default': 'bool',
        'upload_id': 'int'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'api_id': 'apiId',
        'is_default': 'isDefault',
        'upload_id': 'uploadId'
    }

    def __init__(self, id=None, name=None, api_id=None, is_default=None, upload_id=None):  # noqa: E501
        """MapIconModel - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._api_id = None
        self._is_default = None
        self._upload_id = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if api_id is not None:
            self.api_id = api_id
        if is_default is not None:
            self.is_default = is_default
        if upload_id is not None:
            self.upload_id = upload_id

    @property
    def id(self):
        """Gets the id of this MapIconModel.  # noqa: E501

        The system generated unique id  # noqa: E501

        :return: The id of this MapIconModel.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MapIconModel.

        The system generated unique id  # noqa: E501

        :param id: The id of this MapIconModel.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this MapIconModel.  # noqa: E501

        The name for this map icon.  # noqa: E501

        :return: The name of this MapIconModel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MapIconModel.

        The name for this map icon.  # noqa: E501

        :param name: The name of this MapIconModel.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def api_id(self):
        """Gets the api_id of this MapIconModel.  # noqa: E501

        The programmatic, unique id of this map icon.  # noqa: E501

        :return: The api_id of this MapIconModel.  # noqa: E501
        :rtype: str
        """
        return self._api_id

    @api_id.setter
    def api_id(self, api_id):
        """Sets the api_id of this MapIconModel.

        The programmatic, unique id of this map icon.  # noqa: E501

        :param api_id: The api_id of this MapIconModel.  # noqa: E501
        :type: str
        """

        self._api_id = api_id

    @property
    def is_default(self):
        """Gets the is_default of this MapIconModel.  # noqa: E501

        Determines if this is the default icon  # noqa: E501

        :return: The is_default of this MapIconModel.  # noqa: E501
        :rtype: bool
        """
        return self._is_default

    @is_default.setter
    def is_default(self, is_default):
        """Sets the is_default of this MapIconModel.

        Determines if this is the default icon  # noqa: E501

        :param is_default: The is_default of this MapIconModel.  # noqa: E501
        :type: bool
        """

        self._is_default = is_default

    @property
    def upload_id(self):
        """Gets the upload_id of this MapIconModel.  # noqa: E501

        The upload id for the icon  # noqa: E501

        :return: The upload_id of this MapIconModel.  # noqa: E501
        :rtype: int
        """
        return self._upload_id

    @upload_id.setter
    def upload_id(self, upload_id):
        """Sets the upload_id of this MapIconModel.

        The upload id for the icon  # noqa: E501

        :param upload_id: The upload_id of this MapIconModel.  # noqa: E501
        :type: int
        """

        self._upload_id = upload_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MapIconModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MapIconModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
