# coding: utf-8

"""
    Prompt.io APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UpdateCustomerRequestModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'display_name': 'str',
        'global_opt_out': 'bool'
    }

    attribute_map = {
        'display_name': 'displayName',
        'global_opt_out': 'globalOptOut'
    }

    def __init__(self, display_name=None, global_opt_out=None):  # noqa: E501
        """UpdateCustomerRequestModel - a model defined in Swagger"""  # noqa: E501
        self._display_name = None
        self._global_opt_out = None
        self.discriminator = None
        if display_name is not None:
            self.display_name = display_name
        self.global_opt_out = global_opt_out

    @property
    def display_name(self):
        """Gets the display_name of this UpdateCustomerRequestModel.  # noqa: E501

        The display name of this customer  # noqa: E501

        :return: The display_name of this UpdateCustomerRequestModel.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this UpdateCustomerRequestModel.

        The display name of this customer  # noqa: E501

        :param display_name: The display_name of this UpdateCustomerRequestModel.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    @property
    def global_opt_out(self):
        """Gets the global_opt_out of this UpdateCustomerRequestModel.  # noqa: E501

        Sets a customer's global opt out. Global opt out prevents any messaging to this customer  # noqa: E501

        :return: The global_opt_out of this UpdateCustomerRequestModel.  # noqa: E501
        :rtype: bool
        """
        return self._global_opt_out

    @global_opt_out.setter
    def global_opt_out(self, global_opt_out):
        """Sets the global_opt_out of this UpdateCustomerRequestModel.

        Sets a customer's global opt out. Global opt out prevents any messaging to this customer  # noqa: E501

        :param global_opt_out: The global_opt_out of this UpdateCustomerRequestModel.  # noqa: E501
        :type: bool
        """
        if global_opt_out is None:
            raise ValueError("Invalid value for `global_opt_out`, must not be `None`")  # noqa: E501

        self._global_opt_out = global_opt_out

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateCustomerRequestModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateCustomerRequestModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
