# coding: utf-8

"""
    Clothes Warehouse

    This API allows creation and retrieval of clothes   # noqa: E501

    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from clothes_sdk_ashuk203 import schemas  # noqa: F401


class Size(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        enum_value_to_name = {
            "small": "SMALL",
            "medium": "MEDIUM",
            "large": "LARGE",
        }
    
    @schemas.classproperty
    def SMALL(cls):
        return cls("small")
    
    @schemas.classproperty
    def MEDIUM(cls):
        return cls("medium")
    
    @schemas.classproperty
    def LARGE(cls):
        return cls("large")
