"""
    wallet-api

    API  # noqa: E501

    The version of the OpenAPI document: 2.1.514
    Contact: development@wallet.inc
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import wallet
from wallet.model.vs_campaign_generated_message import VSCampaignGeneratedMessage
globals()['VSCampaignGeneratedMessage'] = VSCampaignGeneratedMessage
from wallet.model.vs_campaign_generated_message_pagination import VSCampaignGeneratedMessagePagination


class TestVSCampaignGeneratedMessagePagination(unittest.TestCase):
    """VSCampaignGeneratedMessagePagination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVSCampaignGeneratedMessagePagination(self):
        """Test VSCampaignGeneratedMessagePagination"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VSCampaignGeneratedMessagePagination()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
