"""
    wallet-api

    API  # noqa: E501

    The version of the OpenAPI document: 2.1.514
    Contact: development@wallet.inc
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import wallet
from wallet.model.wt_member import WTMember
globals()['WTMember'] = WTMember
from wallet.model.paginated_wt_members import PaginatedWTMembers


class TestPaginatedWTMembers(unittest.TestCase):
    """PaginatedWTMembers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedWTMembers(self):
        """Test PaginatedWTMembers"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedWTMembers()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
