"""
    wallet-api

    API  # noqa: E501

    The version of the OpenAPI document: 2.1.514
    Contact: development@wallet.inc
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import wallet
from wallet.model.nano_id import NanoID
globals()['NanoID'] = NanoID
from wallet.model.pick_wt_static_voucher_campaign_create_params_exclude_keyof_wt_static_voucher_campaign_create_params_start_date_time_or_expiration_date_time import PickWTStaticVoucherCampaignCreateParamsExcludeKeyofWTStaticVoucherCampaignCreateParamsStartDateTimeOrExpirationDateTime


class TestPickWTStaticVoucherCampaignCreateParamsExcludeKeyofWTStaticVoucherCampaignCreateParamsStartDateTimeOrExpirationDateTime(unittest.TestCase):
    """PickWTStaticVoucherCampaignCreateParamsExcludeKeyofWTStaticVoucherCampaignCreateParamsStartDateTimeOrExpirationDateTime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPickWTStaticVoucherCampaignCreateParamsExcludeKeyofWTStaticVoucherCampaignCreateParamsStartDateTimeOrExpirationDateTime(self):
        """Test PickWTStaticVoucherCampaignCreateParamsExcludeKeyofWTStaticVoucherCampaignCreateParamsStartDateTimeOrExpirationDateTime"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PickWTStaticVoucherCampaignCreateParamsExcludeKeyofWTStaticVoucherCampaignCreateParamsStartDateTimeOrExpirationDateTime()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
