"""
    wallet-api

    API  # noqa: E501

    The version of the OpenAPI document: 2.1.518
    Contact: development@wallet.inc
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import wallet
from wallet.model.ss_nano_id import SSNanoID
globals()['SSNanoID'] = SSNanoID
from wallet.model.wt_imported_list_recipient_from_membership_tier_import import WTImportedListRecipientFromMembershipTierImport


class TestWTImportedListRecipientFromMembershipTierImport(unittest.TestCase):
    """WTImportedListRecipientFromMembershipTierImport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWTImportedListRecipientFromMembershipTierImport(self):
        """Test WTImportedListRecipientFromMembershipTierImport"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WTImportedListRecipientFromMembershipTierImport()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
