"""
    wallet-api

    API  # noqa: E501

    The version of the OpenAPI document: 2.1.514
    Contact: development@wallet.inc
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import wallet
from wallet.model.ss_nano_id import SSNanoID
globals()['SSNanoID'] = SSNanoID
from wallet.model.imported_list import ImportedList


class TestImportedList(unittest.TestCase):
    """ImportedList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImportedList(self):
        """Test ImportedList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ImportedList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
