"""
    wallet-api

    API  # noqa: E501

    The version of the OpenAPI document: 2.1.514
    Contact: development@wallet.inc
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import wallet
from wallet.model.click_funnel_contact import ClickFunnelContact
globals()['ClickFunnelContact'] = ClickFunnelContact
from wallet.model.click_funnel_registration import ClickFunnelRegistration


class TestClickFunnelRegistration(unittest.TestCase):
    """ClickFunnelRegistration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClickFunnelRegistration(self):
        """Test ClickFunnelRegistration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClickFunnelRegistration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
