"""
    wallet-api

    API  # noqa: E501

    The version of the OpenAPI document: 2.1.514
    Contact: development@wallet.inc
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import wallet
from wallet.model.wt_news_article_create_params import WTNewsArticleCreateParams


class TestWTNewsArticleCreateParams(unittest.TestCase):
    """WTNewsArticleCreateParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWTNewsArticleCreateParams(self):
        """Test WTNewsArticleCreateParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WTNewsArticleCreateParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
