"""
    wallet-api

    API  # noqa: E501

    The version of the OpenAPI document: 2.1.514
    Contact: development@wallet.inc
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import wallet
from wallet.model.foreign_key_does_not_exist import ForeignKeyDoesNotExist


class TestForeignKeyDoesNotExist(unittest.TestCase):
    """ForeignKeyDoesNotExist unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testForeignKeyDoesNotExist(self):
        """Test ForeignKeyDoesNotExist"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ForeignKeyDoesNotExist()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
