"""
    wallet-api

    API  # noqa: E501

    The version of the OpenAPI document: 2.1.514
    Contact: development@wallet.inc
    Generated by: https://openapi-generator.tech
"""


import unittest

import wallet
from wallet.api.static_vouchers_api import StaticVouchersApi  # noqa: E501


class TestStaticVouchersApi(unittest.TestCase):
    """StaticVouchersApi unit test stubs"""

    def setUp(self):
        self.api = StaticVouchersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_static_voucher(self):
        """Test case for create_static_voucher

        Create static voucher  # noqa: E501
        """
        pass

    def test_delete_static_voucher(self):
        """Test case for delete_static_voucher

        Delete static voucher  # noqa: E501
        """
        pass

    def test_fetch_reach_stats_of_all_static_vouchers(self):
        """Test case for fetch_reach_stats_of_all_static_vouchers

        Get the reach statistics of all the static vouchers  # noqa: E501
        """
        pass

    def test_fetch_reach_stats_of_individual_static_voucher(self):
        """Test case for fetch_reach_stats_of_individual_static_voucher

        Get the reach statistics of an individual static voucher  # noqa: E501
        """
        pass

    def test_fetch_static_voucher(self):
        """Test case for fetch_static_voucher

        Fetch static voucher  # noqa: E501
        """
        pass

    def test_update_static_voucher(self):
        """Test case for update_static_voucher

        Update static voucher  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
