"""
    wallet-api

    API  # noqa: E501

    The version of the OpenAPI document: 2.1.514
    Contact: development@wallet.inc
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import wallet
from wallet.model.wt_static_voucher_create_params import WTStaticVoucherCreateParams


class TestWTStaticVoucherCreateParams(unittest.TestCase):
    """WTStaticVoucherCreateParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWTStaticVoucherCreateParams(self):
        """Test WTStaticVoucherCreateParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WTStaticVoucherCreateParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
