"""
    wallet-api

    API  # noqa: E501

    The version of the OpenAPI document: 2.1.514
    Contact: development@wallet.inc
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import wallet
from wallet.model.applicable_terminals_any_of5 import ApplicableTerminalsAnyOf5


class TestApplicableTerminalsAnyOf5(unittest.TestCase):
    """ApplicableTerminalsAnyOf5 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicableTerminalsAnyOf5(self):
        """Test ApplicableTerminalsAnyOf5"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApplicableTerminalsAnyOf5()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
