"""
    wallet-api

    API  # noqa: E501

    The version of the OpenAPI document: 2.1.514
    Contact: development@wallet.inc
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import wallet
from wallet.model.nano_id import NanoID
globals()['NanoID'] = NanoID
from wallet.model.create_static_voucher_campaign_with_voucher_with_csv import CreateStaticVoucherCampaignWithVoucherWithCSV


class TestCreateStaticVoucherCampaignWithVoucherWithCSV(unittest.TestCase):
    """CreateStaticVoucherCampaignWithVoucherWithCSV unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateStaticVoucherCampaignWithVoucherWithCSV(self):
        """Test CreateStaticVoucherCampaignWithVoucherWithCSV"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateStaticVoucherCampaignWithVoucherWithCSV()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
