"""
    wallet-api

    API  # noqa: E501

    The version of the OpenAPI document: 2.1.514
    Contact: development@wallet.inc
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import wallet
from wallet.model.ss_nano_id import SSNanoID
from wallet.model.ss_opt_in_source import SSOptInSource
globals()['SSNanoID'] = SSNanoID
globals()['SSOptInSource'] = SSOptInSource
from wallet.model.opt_in_list_subscriber import OptInListSubscriber


class TestOptInListSubscriber(unittest.TestCase):
    """OptInListSubscriber unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOptInListSubscriber(self):
        """Test OptInListSubscriber"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OptInListSubscriber()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
