"""
    wallet-api

    API  # noqa: E501

    The version of the OpenAPI document: 2.1.514
    Contact: development@wallet.inc
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import wallet
from wallet.model.ss_merchant_id import SSMerchantID


class TestSSMerchantID(unittest.TestCase):
    """SSMerchantID unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSSMerchantID(self):
        """Test SSMerchantID"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SSMerchantID()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
