"""
    wallet-api

    API  # noqa: E501

    The version of the OpenAPI document: 2.1.514
    Contact: development@wallet.inc
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import wallet
from wallet.model.merchant_id import MerchantID
from wallet.model.nano_id import NanoID
from wallet.model.status import Status
globals()['MerchantID'] = MerchantID
globals()['NanoID'] = NanoID
globals()['Status'] = Status
from wallet.model.pick_vs_advertisement_credit_scan_exclude_keyof_vs_advertisement_credit_scan_redeemed_at_or_refunded_at import PickVSAdvertisementCreditScanExcludeKeyofVSAdvertisementCreditScanRedeemedAtOrRefundedAt


class TestPickVSAdvertisementCreditScanExcludeKeyofVSAdvertisementCreditScanRedeemedAtOrRefundedAt(unittest.TestCase):
    """PickVSAdvertisementCreditScanExcludeKeyofVSAdvertisementCreditScanRedeemedAtOrRefundedAt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPickVSAdvertisementCreditScanExcludeKeyofVSAdvertisementCreditScanRedeemedAtOrRefundedAt(self):
        """Test PickVSAdvertisementCreditScanExcludeKeyofVSAdvertisementCreditScanRedeemedAtOrRefundedAt"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PickVSAdvertisementCreditScanExcludeKeyofVSAdvertisementCreditScanRedeemedAtOrRefundedAt()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
