"""
    wallet-api

    API  # noqa: E501

    The version of the OpenAPI document: 2.1.514
    Contact: development@wallet.inc
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import wallet
from wallet.model.nano_id import NanoID
globals()['NanoID'] = NanoID
from wallet.model.wt_authentication_request_reset_password import WTAuthenticationRequestResetPassword


class TestWTAuthenticationRequestResetPassword(unittest.TestCase):
    """WTAuthenticationRequestResetPassword unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWTAuthenticationRequestResetPassword(self):
        """Test WTAuthenticationRequestResetPassword"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WTAuthenticationRequestResetPassword()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
