"""
    wallet-api

    API  # noqa: E501

    The version of the OpenAPI document: 2.1.514
    Contact: development@wallet.inc
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import wallet
from wallet.model.status_any_of import StatusAnyOf


class TestStatusAnyOf(unittest.TestCase):
    """StatusAnyOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatusAnyOf(self):
        """Test StatusAnyOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StatusAnyOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
