"""
    wallet-api

    API  # noqa: E501

    The version of the OpenAPI document: 2.1.514
    Contact: development@wallet.inc
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import wallet
from wallet.model.opt_in_list_subscriber import OptInListSubscriber
globals()['OptInListSubscriber'] = OptInListSubscriber
from wallet.model.inline_response2007 import InlineResponse2007


class TestInlineResponse2007(unittest.TestCase):
    """InlineResponse2007 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2007(self):
        """Test InlineResponse2007"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2007()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
