
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-06T19:38:50+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7d6122b3c62858e3cec39293d8c3fa2caa71fa43",
 "version": "0.2.52.post0.dev22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
