from _typeshed import Incomplete
from typing import Optional

class smailPro:
    rapidapi_key: Incomplete
    datas: Incomplete
    def __init__(self, rapidapi_key: str = ...) -> None: ...
    def getAddr(self) -> str: ...
    def rmAddr(self, email) -> None: ...
    def getEmail(self, addr, tries: int = ...) -> Optional[dict]: ...
