
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-08T08:13:30-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "cc2f490b2d20d19cef5d1b128427b7b4e9378443",
 "version": "v0.0.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
