VERSION_YEAR = 2022
VERSION_MONTH = int('12')
VERSION_DAY = int('07')
VERSION_HOUR = int('16')
VERSION_MINUTE = int('49')
MAJOR_VERSION = 1
MINOR_VERSION = 7
PATCH_VERSION = 202212071649
version_date = '2022/12/07 16:49'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
