
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-05T22:34:33-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "95acd945f4461cdc2cffc52b4ed70280dd177b00",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
