
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-10T17:46:09+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "cc1113c8c2b207cd771910cccc0b16cbaf503a2a",
 "version": "0.0.19rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
