# from checkdomain.net
huge_dict = [{"tld": "abogado", "price": 14.99, "authCode": True, "category": 8},
             {"tld": "ac", "price": 7.99, "noticePeriod": 35, "category": 4},
             {"tld": "ac.nz", "price": 6.99, "noticePeriod": 35, "category": 6},
             {"tld": "academy", "price": 3.39, "authCode": True, "category": 8},
             {"tld": "accountant", "price": 8.49, "authCode": True, "category": 8},
             {"tld": "accountants", "price": 8.19, "authCode": True, "category": 8},
             {"tld": "actor", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "adult", "price": 11.69, "authCode": True, "category": 8},
             {"tld": "ae", "price": 8.39, "noticePeriod": 35, "authCode": True, "category": 5},
             {"tld": "aero", "price": 7.89, "noticePeriod": 35, "authCode": True, "category": 7},
             {"tld": "africa", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "ag", "price": 17.99, "noticePeriod": 35, "authCode": True, "category": 2},
             {"tld": "agency", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "ai", "price": 8.39, "transfer": 99, "contractPeriod": 24, "noticePeriod": 60, "authCode": True,
              "category": 2}, {"tld": "al", "price": 8.49, "transfer": 27.132, "contractPeriod": 24, "noticePeriod": 60,
                               "authCode": True, "category": 1},
             {"tld": "alsace", "price": 6.19, "authCode": True, "category": 8},
             {"tld": "am", "price": 8.49, "transfer": 99, "noticePeriod": 35, "authCode": True, "category": 5},
             {"tld": "amsterdam", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "apartments", "price": 4.89, "authCode": True, "category": 8},
             {"tld": "app", "price": 2.99, "authCode": True, "category": 8, "details": {"premiumDomains": True}},
             {"tld": "aq", "price": 8.49, "noticePeriod": 35, "category": 6, "details": {"localOffice": "Antarctica"}},
             {"tld": "archi", "price": 7.39, "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "art", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "as", "price": 12.69, "contractPeriod": 24, "noticePeriod": 35, "category": 6},
             {"tld": "asia", "price": 3.69, "authCode": True, "category": 5},
             {"tld": "associates", "price": 2.99, "authCode": True, "category": 8},
             {"tld": "at", "price": 2.19, "authCode": True, "category": 1},
             {"tld": "attorney", "price": 6.49, "authCode": True, "category": 8},
             {"tld": "auction", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "audio", "price": 19.99, "authCode": True, "category": 8},
             {"tld": "auto", "price": 239.99, "noticePeriod": 60, "authCode": True, "category": 8},
             {"tld": "autos", "price": 78.99, "authCode": True, "category": 8},
             {"tld": "az", "price": 61.49, "transfer": 69.97, "noticePeriod": 60, "category": 5},
             {"tld": "ba", "price": 26.49, "transfer": 107.1, "noticePeriod": 60, "category": 1,
              "details": {"domainLikeCompany": True, "domainLimit": True, "localOffice": "Bosnia and Herzegovina",
                          "adminC": "Bosnia and Herzegovina", "vatId": True, "trustee": 41.412}},
             {"tld": "baby", "price": 7.99, "authCode": True, "category": 8},
             {"tld": "band", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "bar", "price": 6.69, "authCode": True, "category": 8},
             {"tld": "barcelona", "price": 7.39, "authCode": True, "category": 8},
             {"tld": "bargains", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "basketball", "price": 8.59, "authCode": True, "category": 8},
             {"tld": "bayern", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "bb", "price": 48.99, "noticePeriod": 35, "category": 2,
              "details": {"localOffice": "Barbados", "adminC": "Barbados", "passport": True, "vatId": True}},
             {"tld": "be", "price": 1.69, "transfer": 5, "authCode": True, "category": 1},
             {"tld": "beauty", "price": 2.49, "category": 8},
             {"tld": "beer", "price": 3.39, "authCode": True, "category": 8},
             {"tld": "berlin", "price": 4.19, "authCode": True, "category": 8, "details": {"trustee": 1.43}},
             {"tld": "best", "price": 3.49, "authCode": True, "category": 8},
             {"tld": "bet", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "bg", "price": 33.49, "transfer": 112.812, "noticePeriod": 60, "category": 1,
              "details": {"domainLikeCompany": True}},
             {"tld": "bi", "price": 18.49, "noticePeriod": 35, "authCode": True, "category": 4,
              "details": {"premiumDomains": True}}, {"tld": "bible", "price": 29.99, "authCode": True, "category": 8},
             {"tld": "bid", "price": 4.29, "authCode": True, "category": 8},
             {"tld": "bike", "price": 3.69, "authCode": True, "category": 8},
             {"tld": "bingo", "price": 7.99, "authCode": True, "category": 8},
             {"tld": "bio", "price": 5.69, "authCode": True, "category": 8},
             {"tld": "biz", "price": 2.79, "authCode": True, "category": 7},
             {"tld": "biz.fj", "price": 28.49, "transfer": 27.132, "noticePeriod": 35, "category": 6},
             {"tld": "biz.pl", "price": 5.99, "category": 1},
             {"tld": "biz.pr", "price": 24.49, "noticePeriod": 35, "category": 2},
             {"tld": "black", "price": 4.29, "authCode": True, "category": 8},
             {"tld": "blackfriday", "price": 19.69, "authCode": True, "category": 8},
             {"tld": "blog", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "blue", "price": 2.59, "authCode": True, "category": 8},
             {"tld": "bm", "price": 31.49, "noticePeriod": 35, "category": 2, "details": {"adminC": "Bermuda"}},
             {"tld": "bo", "price": 38.99, "transfer": 49, "noticePeriod": 35, "category": 3},
             {"tld": "boats", "price": 28.99, "authCode": True, "category": 8},
             {"tld": "bond", "price": 129, "authCode": True, "category": 8},
             {"tld": "boston", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "boutique", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "brussels", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "bt", "price": 48.99, "noticePeriod": 35, "authCode": True, "category": 5,
              "details": {"commercialRegister": "Bhutan", "domainLikeCompany": True}},
             {"tld": "build", "price": 8.39, "authCode": True, "category": 8},
             {"tld": "builders", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "business", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "buzz", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "by", "price": 12.49, "noticePeriod": 60, "category": 1, "details": {"passport": True}},
             {"tld": "bz", "price": 3.39, "authCode": True, "category": 2},
             {"tld": "bz.it", "price": 1.99, "authCode": True, "category": 1,
              "details": {"passport": True, "onlyEurope": True, "trustee": 4.92}},
             {"tld": "bzh", "price": 8.39, "authCode": True, "category": 8},
             {"tld": "ca", "price": 8.39, "noticePeriod": 60, "authCode": True, "category": 2,
              "details": {"manor": "Canada", "adminC": "Canada"}},
             {"tld": "cab", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "cafe", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "cam", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "camera", "price": 4.59, "authCode": True, "category": 8},
             {"tld": "camp", "price": 4.59, "authCode": True, "category": 8},
             {"tld": "capetown", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "capital", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "car", "price": 234.99, "noticePeriod": 60, "authCode": True, "category": 8},
             {"tld": "cards", "price": 2.99, "authCode": True, "category": 8},
             {"tld": "care", "price": 2.59, "authCode": True, "category": 8},
             {"tld": "career", "price": 16.69, "authCode": True, "category": 8},
             {"tld": "careers", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "cars", "price": 239.99, "noticePeriod": 60, "authCode": True, "category": 8},
             {"tld": "casa", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "cash", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "casino", "price": 12.99, "authCode": True, "category": 8},
             {"tld": "cat", "price": 8.49, "noticePeriod": 35, "authCode": True, "category": 1,
              "details": {"passport": True, "vatId": True}},
             {"tld": "catering", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "cc", "price": 2.49, "noticePeriod": 35, "authCode": True, "category": 6,
              "details": {"premiumDomains": True}}, {"tld": "center", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "ceo", "price": 16.59, "authCode": True, "category": 8},
             {"tld": "cg", "price": 61.49, "noticePeriod": 60, "category": 4},
             {"tld": "ch", "price": 2.49, "authCode": True, "category": 1},
             {"tld": "chat", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "cheap", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "christmas", "price": 8.69, "authCode": True, "category": 8},
             {"tld": "church", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "city", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "cl", "price": 8.49, "noticePeriod": 60, "category": 3},
             {"tld": "claims", "price": 5.99, "authCode": True, "category": 8},
             {"tld": "cleaning", "price": 5.99, "authCode": True, "category": 8},
             {"tld": "click", "price": 1.69, "authCode": True, "category": 8},
             {"tld": "clinic", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "clothing", "price": 6.69, "authCode": True, "category": 8},
             {"tld": "cloud", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "club", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "cm", "price": 13.99, "authCode": True, "category": 4},
             {"tld": "cn", "price": 4.19, "noticePeriod": 35, "authCode": True, "category": 5},
             {"tld": "cn.com", "price": 6.19, "noticePeriod": 75, "authCode": True, "category": 5},
             {"tld": "co", "price": 4.19, "authCode": True, "category": 3},
             {"tld": "co.at", "price": 1.99, "authCode": True, "category": 1},
             {"tld": "co.cr", "price": 12.69, "transfer": 29, "noticePeriod": 35, "category": 2},
             {"tld": "co.gg", "price": 22.49, "category": 1},
             {"tld": "co.hu", "price": 5.99, "transfer": 27.132, "noticePeriod": 60, "category": 1,
              "details": {"adminC": "Hungary", "trustee": 27.132}},
             {"tld": "co.id", "price": 9.99, "noticePeriod": 35, "category": 5,
              "details": {"domainLikeCompany": True, "adminC": "Indonesia"}},
             {"tld": "co.il", "price": 6.99, "transfer": 59.41, "contractPeriod": 24, "noticePeriod": 60,
              "category": 5}, {"tld": "co.im", "price": 4.99, "category": 1},
             {"tld": "co.in", "price": 0.99, "authCode": True, "category": 5},
             {"tld": "co.je", "price": 23.49, "transfer": 19, "noticePeriod": 35, "category": 1},
             {"tld": "co.jp", "price": 19.99, "transfer": 128.27, "noticePeriod": 35, "category": 5,
              "details": {"domainLimit": True, "localOffice": "Japan", "vatId": True}},
             {"tld": "co.kr", "price": 24.99, "transfer": 41.412, "noticePeriod": 35, "authCode": True, "category": 5,
              "details": {"localOffice": "South Korea", "adminC": "South Korea", "trustee": 14.28}},
             {"tld": "co.lc", "price": 7.49, "noticePeriod": 35, "category": 2},
             {"tld": "co.ls", "price": 16.79, "noticePeriod": 60, "category": 4},
             {"tld": "co.mu", "price": 9.99, "noticePeriod": 35, "category": 4},
             {"tld": "co.nz", "price": 4.89, "authCode": True, "category": 6},
             {"tld": "co.om", "price": 42.49, "noticePeriod": 35, "category": 5,
              "details": {"commercialRegister": "Oman", "adminC": "Oman"}},
             {"tld": "co.th", "price": 9.99, "transfer": 22.848, "contractPeriod": 24, "noticePeriod": 35,
              "category": 5,
              "details": {"domainLikeCompany": True, "localOffice": "Thailand", "adminC": "Thailand", "passport": True,
                          "vatId": True}},
             {"tld": "co.tt", "price": 24.99, "transfer": 22.85, "contractPeriod": 36, "noticePeriod": 35,
              "category": 2}, {"tld": "co.uk", "price": 1.69, "transfer": 29, "contractPeriod": 24, "category": 1},
             {"tld": "co.ve", "price": 12.99, "transfer": 41.412, "noticePeriod": 60, "category": 3},
             {"tld": "co.za", "price": 3.99, "category": 4},
             {"tld": "coach", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "codes", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "coffee", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "college", "price": 8.19, "authCode": True, "category": 8},
             {"tld": "cologne", "price": 2.59, "authCode": True, "category": 8},
             {"tld": "com", "price": 1.69, "authCode": True, "category": 7},
             {"tld": "com.ag", "price": 8.39, "category": 2},
             {"tld": "com.ai", "price": 9.99, "contractPeriod": 24, "noticePeriod": 35, "category": 2},
             {"tld": "com.ar", "price": 11.99, "transfer": 71.4, "noticePeriod": 35, "category": 3,
              "details": {"trustee": 41.412}},
             {"tld": "com.au", "price": 10.49, "contractPeriod": 24, "noticePeriod": 60, "authCode": True,
              "category": 6, "details": {"domainLikeCompany": True, "localOffice": "Australia", "adminC": "Australia",
                                         "passport": True}},
             {"tld": "com.bo", "price": 34.49, "transfer": 49, "noticePeriod": 35, "category": 3,
              "details": {"localOffice": "Bolivia", "adminC": "Bolivia"}},
             {"tld": "com.br", "price": 13.39, "transfer": 12.852, "noticePeriod": 35, "category": 3,
              "details": {"localOffice": "Brazil", "adminC": "Brazil", "vatId": True, "trustee": 141.372}},
             {"tld": "com.cn", "price": 3.99, "noticePeriod": 35, "authCode": True, "category": 5},
             {"tld": "com.co", "price": 3.99, "contractPeriod": 24, "noticePeriod": 35, "category": 3,
              "details": {"localOffice": "Colombia", "adminC": "Colombia"}},
             {"tld": "com.cu", "price": 59.99, "transfer": 468.38, "noticePeriod": 35, "category": 2,
              "details": {"localOffice": "Cuba", "adminC": "Cuba"}},
             {"tld": "com.cy", "price": 20.49, "noticePeriod": 35, "category": 1,
              "details": {"commercialRegister": "Cyprus", "domainLikeCompany": True, "domainLimit": True,
                          "localOffice": "Cyprus", "adminC": "Cyprus", "passport": True, "vatId": True}},
             {"tld": "com.de", "price": 2.49, "authCode": True, "category": 1},
             {"tld": "com.do", "price": 7.69, "contractPeriod": 24, "noticePeriod": 35, "category": 2,
              "details": {"passport": True}}, {"tld": "com.ec", "price": 19.99, "noticePeriod": 35, "category": 3,
                                               "details": {"commercialRegister": "Ecuador"}},
             {"tld": "com.eg", "price": 83.49, "noticePeriod": 75, "category": 4,
              "details": {"passport": True, "vatId": True}},
             {"tld": "com.es", "price": 3.99, "category": 1, "details": {"passport": True, "vatId": True}},
             {"tld": "com.fj", "price": 28.49, "transfer": 27.132, "noticePeriod": 35, "category": 6},
             {"tld": "com.fr", "price": 4.99, "noticePeriod": 35, "category": 1,
              "details": {"localOffice": "France", "adminC": "France"}},
             {"tld": "com.gi", "price": 41.49, "transfer": 31.42, "noticePeriod": 35, "category": 1},
             {"tld": "com.gr", "price": 4.99, "contractPeriod": 24, "noticePeriod": 60, "category": 1},
             {"tld": "com.gt", "price": 7.49, "transfer": 39, "contractPeriod": 24, "noticePeriod": 60, "category": 2},
             {"tld": "com.hk", "price": 9.99, "transfer": 41.412, "noticePeriod": 60, "authCode": True, "category": 5,
              "details": {"commercialRegister": "Hong Kong SAR China", "localOffice": "Hong Kong SAR China",
                          "adminC": "Hong Kong SAR China", "passport": True}},
             {"tld": "com.hn", "price": 12.99, "category": 2},
             {"tld": "com.hr", "price": 8.49, "transfer": 28.56, "noticePeriod": 35, "category": 1},
             {"tld": "com.im", "price": 4.99, "category": 1},
             {"tld": "com.ki", "price": 19.99, "noticePeriod": 35, "category": 6},
             {"tld": "com.lb", "price": 9.99, "noticePeriod": 35, "category": 5,
              "details": {"domainLikeCompany": True, "localOffice": "Lebanon", "adminC": "Lebanon", "passport": True,
                          "vatId": True, "premiumDomains": True}},
             {"tld": "com.lc", "price": 7.49, "noticePeriod": 35, "category": 2},
             {"tld": "com.lv", "price": 8.29, "noticePeriod": 60, "category": 1},
             {"tld": "com.mt", "price": 18.99, "transfer": 49, "noticePeriod": 60, "category": 1,
              "details": {"domainLikeCompany": True, "passport": True, "vatId": True}},
             {"tld": "com.mu", "price": 8.49, "category": 4},
             {"tld": "com.mx", "price": 7.99, "noticePeriod": 60, "category": 2},
             {"tld": "com.my", "price": 7.99, "transfer": 86.82, "noticePeriod": 35, "category": 5,
              "details": {"localOffice": "Malaysia", "adminC": "Malaysia", "trustee": 90.96}},
             {"tld": "com.ng", "price": 17.49, "noticePeriod": 60, "category": 4,
              "details": {"domainLimit": True, "premiumDomains": True}},
             {"tld": "com.ni", "price": 24.49, "transfer": 28.56, "noticePeriod": 60, "category": 2},
             {"tld": "com.pa", "price": 14.99, "transfer": 14.28, "contractPeriod": 24, "noticePeriod": 60,
              "category": 2},
             {"tld": "com.pe", "price": 14.99, "transfer": 45.696, "noticePeriod": 35, "authCode": True, "category": 3},
             {"tld": "com.ph", "price": 7.99, "transfer": 35.7, "contractPeriod": 24, "noticePeriod": 35,
              "category": 5}, {"tld": "com.pk", "price": 8.49, "category": 5},
             {"tld": "com.pl", "price": 5.99, "noticePeriod": 35, "authCode": True, "category": 1},
             {"tld": "com.pr", "price": 24.99, "noticePeriod": 35, "category": 2},
             {"tld": "com.ps", "price": 7.99, "transfer": 11.42, "noticePeriod": 35, "category": 5,
              "details": {"premiumDomains": True}}, {"tld": "com.pt", "price": 7.99, "noticePeriod": 60, "category": 1,
                                                     "details": {"passport": True, "vatId": True}},
             {"tld": "com.py", "price": 16.69, "noticePeriod": 35, "category": 3},
             {"tld": "com.qa", "price": 24.99, "noticePeriod": 35, "category": 5,
              "details": {"commercialRegister": "Qatar", "localOffice": "Qatar", "adminC": "Qatar", "trustee": 112.81}},
             {"tld": "com.ro", "price": 11.49, "noticePeriod": 60, "authCode": True, "category": 1,
              "details": {"vatId": True}}, {"tld": "com.sc", "price": 14.99, "noticePeriod": 35, "category": 4},
             {"tld": "com.sg", "price": 6.69, "transfer": 38.4, "authCode": True, "category": 5,
              "details": {"localOffice": "Singapore", "adminC": "Singapore", "trustee": 19}},
             {"tld": "com.sv", "price": 19.49, "transfer": 21.42, "noticePeriod": 60, "category": 2,
              "details": {"localOffice": "El Salvador", "adminC": "El Salvador"}},
             {"tld": "com.tr", "price": 7.49, "transfer": 21.42, "noticePeriod": 60, "category": 5,
              "details": {"domainLikeCompany": True, "letterOfIntent": True}},
             {"tld": "com.tt", "price": 24.99, "transfer": 22.85, "contractPeriod": 36, "noticePeriod": 35,
              "category": 2}, {"tld": "com.tw", "price": 3.99, "noticePeriod": 35, "authCode": True, "category": 5},
             {"tld": "com.ua", "price": 8.39, "noticePeriod": 35, "authCode": True, "category": 1},
             {"tld": "com.uy", "price": 22.49, "noticePeriod": 35, "category": 3,
              "details": {"localOffice": "Uruguay", "adminC": "Uruguay"}},
             {"tld": "com.vc", "price": 6.99, "transfer": 54.42, "noticePeriod": 35, "category": 2},
             {"tld": "com.ve", "price": 11.99, "transfer": 41.412, "noticePeriod": 60, "category": 3},
             {"tld": "com.vn", "price": 17.99, "noticePeriod": 60, "category": 5},
             {"tld": "community", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "company", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "compare", "price": 5.49, "authCode": True, "category": 8},
             {"tld": "computer", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "condos", "price": 5.99, "authCode": True, "category": 8},
             {"tld": "construction", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "consulting", "price": 6.19, "authCode": True, "category": 8},
             {"tld": "contact", "price": 1.99, "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "contractors", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "cooking", "price": 4.69, "authCode": True, "category": 8},
             {"tld": "cool", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "coop", "price": 14.19, "noticePeriod": 35, "authCode": True, "category": 7},
             {"tld": "corsica", "price": 5.69, "authCode": True, "category": 8},
             {"tld": "country", "price": 4.69, "authCode": True, "category": 8},
             {"tld": "coupons", "price": 6.69, "authCode": True, "category": 8},
             {"tld": "courses", "price": 4.89, "authCode": True, "category": 8},
             {"tld": "cr", "price": 15.99, "transfer": 21.42, "noticePeriod": 60, "category": 2,
              "details": {"passport": True, "vatId": True}},
             {"tld": "credit", "price": 12.99, "authCode": True, "category": 8},
             {"tld": "creditcard", "price": 15.99, "authCode": True, "category": 8},
             {"tld": "cricket", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "cruises", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "cu", "price": 88.99, "noticePeriod": 35, "category": 2,
              "details": {"localOffice": "Cuba", "adminC": "Cuba"}},
             {"tld": "cx", "price": 10.49, "transfer": 27.13, "noticePeriod": 35, "authCode": True, "category": 6},
             {"tld": "cymru", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "cyou", "price": 1.69, "authCode": True, "category": 8},
             {"tld": "cz", "price": 3.99, "noticePeriod": 60, "authCode": True, "category": 1},
             {"tld": "dance", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "date", "price": 3.49, "authCode": True, "category": 8},
             {"tld": "dating", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "de", "price": 1.29, "authCode": True, "category": 1},
             {"tld": "dealer", "price": 399, "authCode": True, "category": 8},
             {"tld": "deals", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "degree", "price": 4.69, "authCode": True, "category": 8},
             {"tld": "delivery", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "democrat", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "dental", "price": 4.89, "authCode": True, "category": 8},
             {"tld": "dentist", "price": 5.99, "authCode": True, "category": 8},
             {"tld": "desi", "price": 3.49, "authCode": True, "category": 8},
             {"tld": "design", "price": 4.89, "authCode": True, "category": 8},
             {"tld": "dev", "price": 2.99, "authCode": True, "category": 8, "details": {"premiumDomains": True}},
             {"tld": "diamonds", "price": 5.99, "authCode": True, "category": 8},
             {"tld": "diet", "price": 19.69, "authCode": True, "category": 8},
             {"tld": "digital", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "direct", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "directory", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "discount", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "dj", "price": 7.99, "transfer": 11.424, "noticePeriod": 35, "category": 4},
             {"tld": "dk", "price": 2.49, "transfer": 19, "category": 1, "details": {"vatId": True}},
             {"tld": "do", "price": 15.49, "contractPeriod": 24, "noticePeriod": 35, "category": 2,
              "details": {"passport": True}}, {"tld": "doctor", "price": 12.19, "authCode": True, "category": 8},
             {"tld": "dog", "price": 6.69, "authCode": True, "category": 8},
             {"tld": "domains", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "download", "price": 4.69, "authCode": True, "category": 8},
             {"tld": "durban", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "dz", "price": 28.99, "noticePeriod": 60, "category": 4,
              "details": {"localOffice": "Algeria", "vatId": True}},
             {"tld": "earth", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "ec", "price": 14.99, "transfer": 14.28, "category": 3,
              "details": {"commercialRegister": "Ecuador"}},
             {"tld": "eco", "price": 10.59, "authCode": True, "category": 8},
             {"tld": "edu.it", "price": 1.99, "authCode": True, "category": 1, "details": {"onlyEurope": True}},
             {"tld": "education", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "ee", "price": 12.49, "transfer": 29, "noticePeriod": 60, "authCode": True, "category": 1,
              "details": {"passport": True, "vatId": True}},
             {"tld": "eg", "price": 83.49, "noticePeriod": 75, "authCode": True, "category": 4,
              "details": {"adminC": "Egypt", "vatId": True}},
             {"tld": "email", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "energy", "price": 8.19, "authCode": True, "category": 8},
             {"tld": "engineer", "price": 4.19, "authCode": True, "category": 8},
             {"tld": "engineering", "price": 5.99, "authCode": True, "category": 8},
             {"tld": "enterprises", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "equipment", "price": 2.59, "authCode": True, "category": 8},
             {"tld": "es", "price": 2.59, "noticePeriod": 35, "category": 1,
              "details": {"passport": True, "vatId": True}},
             {"tld": "estate", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "eu", "price": 1.79, "authCode": True, "category": 1,
              "details": {"onlyEurope": True, "trustee": 4.92}},
             {"tld": "eus", "price": 14.99, "authCode": True, "category": 8},
             {"tld": "events", "price": 3.49, "authCode": True, "category": 8},
             {"tld": "exchange", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "expert", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "exposed", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "express", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "fail", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "faith", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "family", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "fan", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "fans", "price": 1.79, "authCode": True, "category": 8},
             {"tld": "farm", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "fashion", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "feedback", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "fi", "price": 15.49, "noticePeriod": 35, "authCode": True, "category": 1},
             {"tld": "film", "price": 8.39, "authCode": True, "category": 8, "details": {"domainLikeCompany": True}},
             {"tld": "finance", "price": 5.89, "authCode": True, "category": 8},
             {"tld": "financial", "price": 5.89, "authCode": True, "category": 8},
             {"tld": "firm.in", "price": 1.29, "category": 5},
             {"tld": "fish", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "fishing", "price": 3.49, "authCode": True, "category": 8},
             {"tld": "fit", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "fitness", "price": 3.39, "authCode": True, "category": 8},
             {"tld": "flights", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "florist", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "flowers", "price": 19.69, "authCode": True, "category": 8},
             {"tld": "fm", "price": 8.39, "noticePeriod": 35, "authCode": True, "category": 6},
             {"tld": "fo", "price": 25.99, "noticePeriod": 35, "category": 1,
              "details": {"passport": True, "vatId": True}},
             {"tld": "football", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "forsale", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "forum", "price": 169, "authCode": True, "category": 8},
             {"tld": "foundation", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "fr", "price": 4.99, "noticePeriod": 35, "authCode": True, "category": 1,
              "details": {"onlyEurope": True, "trustee": 27.132}},
             {"tld": "frl", "price": 6.59, "authCode": True, "category": 8},
             {"tld": "fun", "price": 2.59, "authCode": True, "category": 8},
             {"tld": "fund", "price": 8.49, "authCode": True, "category": 8},
             {"tld": "furniture", "price": 5.99, "authCode": True, "category": 8},
             {"tld": "futbol", "price": 1.69, "authCode": True, "category": 8},
             {"tld": "fyi", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "gal", "price": 12.59, "authCode": True, "category": 8},
             {"tld": "gallery", "price": 2.59, "authCode": True, "category": 8},
             {"tld": "game", "price": 38.99, "authCode": True, "category": 8},
             {"tld": "games", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "garden", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "gay", "price": 7.99, "authCode": True, "category": 8},
             {"tld": "gd", "price": 4.99, "authCode": True, "category": 2},
             {"tld": "ge", "price": 34.99, "setup": 59, "transfer": 27.132, "noticePeriod": 60, "category": 5,
              "details": {"localOffice": "Georgia", "adminC": "Georgia", "trustee": 41.412}},
             {"tld": "geek.nz", "price": 4.99, "noticePeriod": 35, "category": 6,
              "details": {"domainLikeCompany": True}},
             {"tld": "gen.nz", "price": 4.99, "noticePeriod": 35, "category": 6},
             {"tld": "gent", "price": 4.19, "authCode": True, "category": 8},
             {"tld": "gg", "price": 27.49, "category": 1},
             {"tld": "gi", "price": 19.99, "transfer": 29.42, "contractPeriod": 24, "noticePeriod": 35, "category": 1,
              "details": {"passport": True, "vatId": True}},
             {"tld": "gift", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "gifts", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "gives", "price": 4.19, "authCode": True, "category": 8},
             {"tld": "gl", "price": 8.19, "noticePeriod": 60, "authCode": True, "category": 2},
             {"tld": "glass", "price": 6.69, "authCode": True, "category": 8},
             {"tld": "global", "price": 6.69, "authCode": True, "category": 8},
             {"tld": "gmbh", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "gold", "price": 12.99, "authCode": True, "category": 8},
             {"tld": "golf", "price": 4.89, "authCode": True, "category": 8},
             {"tld": "gp", "price": 16.99, "transfer": 41.412, "noticePeriod": 60, "category": 2,
              "details": {"premiumDomains": True}},
             {"tld": "gr", "price": 3.39, "contractPeriod": 24, "noticePeriod": 60, "authCode": True, "category": 1},
             {"tld": "graphics", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "gratis", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "green", "price": 8.19, "authCode": True, "category": 8},
             {"tld": "gripe", "price": 4.19, "authCode": True, "category": 8},
             {"tld": "group", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "gs", "price": 4.99, "category": 3},
             {"tld": "gt", "price": 22.49, "contractPeriod": 24, "noticePeriod": 35, "category": 2},
             {"tld": "guide", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "guitars", "price": 19.69, "authCode": True, "category": 8},
             {"tld": "guru", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "gy", "price": 8.49, "transfer": 41.412, "authCode": True, "category": 3},
             {"tld": "hair", "price": 2.49, "category": 8},
             {"tld": "hamburg", "price": 4.19, "authCode": True, "category": 8},
             {"tld": "haus", "price": 3.49, "authCode": True, "category": 8},
             {"tld": "health", "price": 11.69, "authCode": True, "category": 8},
             {"tld": "healthcare", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "help", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "hiphop", "price": 19.69, "authCode": True, "category": 8},
             {"tld": "hiv", "price": 19.99, "authCode": True, "category": 8},
             {"tld": "hk", "price": 6.69, "transfer": 27.132, "noticePeriod": 60, "authCode": True, "category": 5,
              "details": {"passport": True, "vatId": True}},
             {"tld": "hm", "price": 12.19, "transfer": 34.272, "noticePeriod": 35, "authCode": True, "category": 6},
             {"tld": "hn", "price": 8.39, "authCode": True, "category": 2},
             {"tld": "hockey", "price": 4.89, "authCode": True, "category": 8},
             {"tld": "holdings", "price": 6.69, "authCode": True, "category": 8},
             {"tld": "holiday", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "homes", "price": 19.19, "authCode": True, "category": 8, "details": {"premiumDomains": True}},
             {"tld": "horse", "price": 2.59, "authCode": True, "category": 8},
             {"tld": "hospital", "price": 6.69, "authCode": True, "category": 8},
             {"tld": "host", "price": 8.19, "authCode": True, "category": 8},
             {"tld": "hosting", "price": 58.99, "authCode": True, "category": 8},
             {"tld": "house", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "how", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "hr", "price": 37.49, "noticePeriod": 35, "category": 1,
              "details": {"passport": True, "vatId": True, "trustee": 141.372}},
             {"tld": "ht", "price": 10.89, "transfer": 59, "noticePeriod": 60, "authCode": True, "category": 2},
             {"tld": "hu", "price": 8.49, "noticePeriod": 60, "category": 1,
              "details": {"adminC": "Hungary", "passport": True, "vatId": True, "trustee": 27.13}},
             {"tld": "icu", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "ie", "price": 11.99, "transfer": 14.28, "noticePeriod": 60, "authCode": True, "category": 1,
              "details": {"localOffice": "Ireland"}}, {"tld": "im", "price": 4.19, "authCode": True, "category": 1},
             {"tld": "immo", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "immobilien", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "in", "price": 1.59, "authCode": True, "category": 5},
             {"tld": "in.th", "price": 9.99, "transfer": 22.848, "contractPeriod": 24, "noticePeriod": 35,
              "category": 5, "details": {"localOffice": "Thailand", "adminC": "Thailand", "passport": True}},
             {"tld": "inc", "price": 329, "authCode": True, "category": 8},
             {"tld": "ind.in", "price": 0.99, "category": 5},
             {"tld": "industries", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "info", "price": 1.69, "authCode": True, "category": 7},
             {"tld": "info.ec", "price": 7.69, "noticePeriod": 35, "authCode": True, "category": 3,
              "details": {"commercialRegister": "Ecuador"}},
             {"tld": "info.fj", "price": 24.99, "transfer": 27.132, "noticePeriod": 35, "category": 6},
             {"tld": "info.pl", "price": 4.99, "category": 1},
             {"tld": "info.pr", "price": 22.99, "noticePeriod": 35, "category": 2},
             {"tld": "ink", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "institute", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "insure", "price": 5.99, "authCode": True, "category": 8},
             {"tld": "international", "price": 2.69, "authCode": True, "category": 8},
             {"tld": "investments", "price": 8.19, "authCode": True, "category": 8},
             {"tld": "io", "price": 7.99, "authCode": True, "category": 5},
             {"tld": "irish", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "is", "price": 6.69, "noticePeriod": 75, "category": 1},
             {"tld": "isla.pr", "price": 4.29, "noticePeriod": 35, "category": 2},
             {"tld": "ist", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "istanbul", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "it", "price": 1.99, "authCode": True, "category": 1,
              "details": {"passport": True, "vatId": True, "onlyEurope": True, "trustee": 4.92}},
             {"tld": "je", "price": 25.99, "category": 1},
             {"tld": "jetzt", "price": 1.69, "authCode": True, "category": 8},
             {"tld": "jewelry", "price": 6.69, "authCode": True, "category": 8},
             {"tld": "jo", "price": 28.49, "noticePeriod": 60, "authCode": True, "category": 5,
              "details": {"adminC": "Jordan"}},
             {"tld": "jobs", "price": 16.69, "authCode": True, "category": 7, "details": {"domainLikeCompany": True}},
             {"tld": "joburg", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "jp", "price": 12.49, "noticePeriod": 35, "category": 5,
              "details": {"adminC": "Japan", "vatId": True, "trustee": 9.48}},
             {"tld": "juegos", "price": 58.99, "authCode": True, "category": 8},
             {"tld": "kaufen", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "ki", "price": 98.99, "noticePeriod": 35, "category": 6},
             {"tld": "kim", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "kitchen", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "kiwi", "price": 2.99, "authCode": True, "category": 8},
             {"tld": "koeln", "price": 2.59, "authCode": True, "category": 8},
             {"tld": "kr", "price": 9.99, "transfer": 42, "noticePeriod": 35, "authCode": True, "category": 5,
              "details": {"localOffice": "South Korea", "adminC": "South Korea", "trustee": 14.28}},
             {"tld": "krd", "price": 14.99, "authCode": True, "category": 8},
             {"tld": "kyoto", "price": 16.59, "authCode": True, "category": 8},
             {"tld": "kz", "price": 16.49, "transfer": 29, "noticePeriod": 35, "authCode": True, "category": 5},
             {"tld": "la", "price": 3.99, "noticePeriod": 35, "authCode": True, "category": 5},
             {"tld": "land", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "lat", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "law", "price": 28.99, "authCode": True, "category": 8},
             {"tld": "law.pro", "price": 28.99, "category": 7},
             {"tld": "lawyer", "price": 6.59, "authCode": True, "category": 8},
             {"tld": "lc", "price": 7.99, "noticePeriod": 35, "category": 2},
             {"tld": "lease", "price": 8.39, "authCode": True, "category": 8},
             {"tld": "legal", "price": 4.89, "authCode": True, "category": 8},
             {"tld": "lgbt", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "li", "price": 1.99, "authCode": True, "category": 1},
             {"tld": "life", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "lighting", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "limited", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "limo", "price": 7.99, "authCode": True, "category": 8},
             {"tld": "link", "price": 1.69, "authCode": True, "category": 8},
             {"tld": "live", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "llc", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "loan", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "loans", "price": 14.99, "authCode": True, "category": 8},
             {"tld": "lol", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "london", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "lotto", "price": 248.99, "authCode": True, "category": 8},
             {"tld": "love", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "lt", "price": 5.99, "noticePeriod": 60, "category": 1},
             {"tld": "ltd", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "ltd.gi", "price": 30.49, "transfer": 11.42, "noticePeriod": 75, "category": 1,
              "details": {"domainLikeCompany": True, "localOffice": "Gibraltar"}},
             {"tld": "ltd.uk", "price": 1.69, "contractPeriod": 24, "noticePeriod": 35, "authCode": True, "category": 1,
              "details": {"manor": "United Kingdom", "localOffice": "United Kingdom", "passport": True}},
             {"tld": "ltda", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "lu", "price": 6.99, "category": 1},
             {"tld": "luxe", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "luxury", "price": 5.49, "authCode": True, "category": 8},
             {"tld": "lv", "price": 4.99, "noticePeriod": 60, "authCode": True, "category": 1},
             {"tld": "ly", "price": 19.99, "noticePeriod": 60, "category": 4},
             {"tld": "ma", "price": 16.69, "noticePeriod": 60, "authCode": True, "category": 4},
             {"tld": "madrid", "price": 7.99, "authCode": True, "category": 8},
             {"tld": "maison", "price": 6.69, "authCode": True, "category": 8},
             {"tld": "management", "price": 2.99, "authCode": True, "category": 8},
             {"tld": "market", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "marketing", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "markets", "price": 2.99, "authCode": True, "category": 8},
             {"tld": "mba", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "mc", "price": 21.99, "noticePeriod": 60, "category": 1,
              "details": {"domainLikeCompany": True, "localOffice": "Monaco", "adminC": "Monaco", "vatId": True}},
             {"tld": "md", "price": 19.99, "noticePeriod": 35, "category": 1},
             {"tld": "me", "price": 2.99, "authCode": True, "category": 1},
             {"tld": "me.uk", "price": 1.69, "contractPeriod": 24, "noticePeriod": 35, "category": 1},
             {"tld": "med.pro", "price": 34.99, "category": 7},
             {"tld": "media", "price": 3.49, "authCode": True, "category": 8},
             {"tld": "melbourne", "price": 9.99, "authCode": True, "category": 8},
             {"tld": "memorial", "price": 7.99, "authCode": True, "category": 8},
             {"tld": "men", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "menu", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "mg", "price": 19.99, "category": 4},
             {"tld": "miami", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "mn", "price": 6.69, "category": 5},
             {"tld": "mobi", "price": 2.49, "authCode": True, "category": 7},
             {"tld": "moda", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "moe", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "mom", "price": 4.19, "authCode": True, "category": 8},
             {"tld": "money", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "monster", "price": 2.99, "authCode": True, "category": 8},
             {"tld": "mortgage", "price": 5.99, "authCode": True, "category": 8},
             {"tld": "motorcycles", "price": 48.99, "authCode": True, "category": 8,
              "details": {"domainLikeCompany": True}},
             {"tld": "movie", "price": 28.99, "authCode": True, "category": 8},
             {"tld": "mp", "price": 14.99, "noticePeriod": 60, "category": 2},
             {"tld": "mq", "price": 18.49, "transfer": 19, "noticePeriod": 60, "category": 2},
             {"tld": "ms", "price": 4.99, "noticePeriod": 35, "authCode": True, "category": 2},
             {"tld": "mu", "price": 8.59, "category": 4},
             {"tld": "museum", "price": 48.99, "contractPeriod": 24, "noticePeriod": 35, "authCode": True,
              "category": 7},
             {"tld": "mw", "price": 16.99, "contractPeriod": 36, "noticePeriod": 35, "authCode": True, "category": 4},
             {"tld": "mx", "price": 8.49, "noticePeriod": 60, "authCode": True, "category": 2},
             {"tld": "my", "price": 14.99, "transfer": 14.28, "noticePeriod": 35, "category": 5,
              "details": {"localOffice": "Malaysia", "adminC": "Malaysia", "trustee": 27.132}},
             {"tld": "nagoya", "price": 4.19, "authCode": True, "category": 8},
             {"tld": "name", "price": 1.69, "noticePeriod": 35, "authCode": True, "category": 7},
             {"tld": "name.fj", "price": 26.49, "transfer": 171.36, "noticePeriod": 35, "category": 6},
             {"tld": "name.pr", "price": 22.99, "noticePeriod": 35, "authCode": True, "category": 2},
             {"tld": "name.tr", "price": 0.99, "transfer": 39, "noticePeriod": 75, "category": 5,
              "details": {"premiumDomains": True}}, {"tld": "net", "price": 2.19, "authCode": True, "category": 7},
             {"tld": "net.ag", "price": 8.39, "category": 2},
             {"tld": "net.ai", "price": 22.99, "transfer": 29, "contractPeriod": 24, "noticePeriod": 35, "category": 2},
             {"tld": "net.au", "price": 14.99, "contractPeriod": 24, "noticePeriod": 60, "category": 6,
              "details": {"domainLikeCompany": True, "localOffice": "Australia", "adminC": "Australia",
                          "passport": True}}, {"tld": "net.cn", "price": 3.99, "authCode": True, "category": 5},
             {"tld": "net.fj", "price": 24.99, "transfer": 27.132, "noticePeriod": 35, "category": 6},
             {"tld": "net.gg", "price": 11.69, "category": 1},
             {"tld": "net.hk", "price": 13.49, "transfer": 55.692, "noticePeriod": 60, "category": 5,
              "details": {"passport": True}}, {"tld": "net.hn", "price": 13.99, "category": 2},
             {"tld": "net.im", "price": 3.99, "category": 1}, {"tld": "net.in", "price": 0.99, "category": 5},
             {"tld": "net.je", "price": 25.99, "transfer": 19, "noticePeriod": 35, "category": 1},
             {"tld": "net.ki", "price": 19.99, "noticePeriod": 35, "category": 6},
             {"tld": "net.lc", "price": 7.99, "noticePeriod": 35, "category": 2},
             {"tld": "net.lv", "price": 8.29, "noticePeriod": 60, "authCode": True, "category": 1},
             {"tld": "net.mu", "price": 9.99, "category": 4},
             {"tld": "net.my", "price": 9.99, "transfer": 86.82, "noticePeriod": 35, "category": 5,
              "details": {"localOffice": "Malaysia", "adminC": "Malaysia"}},
             {"tld": "net.nz", "price": 4.99, "authCode": True, "category": 6},
             {"tld": "net.ph", "price": 4.99, "transfer": 35.7, "contractPeriod": 24, "noticePeriod": 35,
              "category": 5}, {"tld": "net.pl", "price": 3.99, "category": 1},
             {"tld": "net.pr", "price": 27.49, "noticePeriod": 35, "category": 2},
             {"tld": "net.ps", "price": 7.99, "transfer": 11.42, "noticePeriod": 35, "category": 5,
              "details": {"premiumDomains": True}},
             {"tld": "net.sc", "price": 12.59, "noticePeriod": 35, "category": 4},
             {"tld": "net.tt", "price": 13.49, "transfer": 21.42, "contractPeriod": 36, "noticePeriod": 60,
              "category": 2}, {"tld": "net.tw", "price": 4.99, "noticePeriod": 35, "category": 5},
             {"tld": "net.uk", "price": 1.69, "contractPeriod": 24, "category": 1,
              "details": {"localOffice": "United Kingdom", "adminC": "United Kingdom", "passport": True}},
             {"tld": "net.vc", "price": 7.99, "transfer": 11.42, "noticePeriod": 35, "category": 2},
             {"tld": "net.za", "price": 3.99, "category": 4},
             {"tld": "network", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "new", "price": 89, "authCode": True, "category": 8},
             {"tld": "news", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "ninja", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "nl", "price": 1.69, "authCode": True, "category": 1},
             {"tld": "no", "price": 10.49, "noticePeriod": 35, "category": 1,
              "details": {"domainLimit": True, "localOffice": "Norway", "vatId": True, "trustee": 255.6}},
             {"tld": "nom.ag", "price": 8.39, "noticePeriod": 35, "authCode": True, "category": 2},
             {"tld": "nom.es", "price": 1.99, "category": 1},
             {"tld": "nrw", "price": 4.89, "authCode": True, "category": 8, "details": {"trustee": 207.06}},
             {"tld": "nu", "price": 3.39, "contractPeriod": 24, "noticePeriod": 35, "authCode": True, "category": 6,
              "details": {"passport": True, "vatId": True}},
             {"tld": "nyc", "price": 5.99, "authCode": True, "category": 8},
             {"tld": "nz", "price": 4.89, "authCode": True, "category": 6},
             {"tld": "observer", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "off.ai", "price": 14.99, "contractPeriod": 24, "noticePeriod": 35, "authCode": True,
              "category": 2}, {"tld": "okinawa", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "one", "price": 1.69, "authCode": True, "category": 8},
             {"tld": "onl", "price": 2.59, "authCode": True, "category": 8},
             {"tld": "online", "price": 5.99, "authCode": True, "category": 8, "discount": {"price": 0.58,
                                                                                            "hint": "The .online-domain costs in the first year only 0,58EUR\/month. Thereafter 5,99EUR\/month."}},
             {"tld": "ooo", "price": 6.79, "authCode": True, "category": 8},
             {"tld": "or.at", "price": 2.99, "authCode": True, "category": 1},
             {"tld": "org", "price": 1.99, "authCode": True, "category": 7},
             {"tld": "org.ag", "price": 8.49, "category": 2},
             {"tld": "org.ai", "price": 29.99, "transfer": 29, "contractPeriod": 24, "noticePeriod": 35, "category": 2},
             {"tld": "org.cn", "price": 3.99, "noticePeriod": 35, "authCode": True, "category": 5},
             {"tld": "org.es", "price": 2.99, "category": 1},
             {"tld": "org.fj", "price": 24.99, "transfer": 27.132, "noticePeriod": 35, "category": 6},
             {"tld": "org.gg", "price": 11.69, "noticePeriod": 35, "category": 1},
             {"tld": "org.gi", "price": 41.49, "transfer": 11.424, "noticePeriod": 35, "category": 1,
              "details": {"domainLikeCompany": True}},
             {"tld": "org.hk", "price": 17.49, "transfer": 55.692, "noticePeriod": 60, "category": 5,
              "details": {"passport": True}}, {"tld": "org.hn", "price": 12.99, "category": 2},
             {"tld": "org.il", "price": 8.19, "transfer": 69, "noticePeriod": 35, "category": 5},
             {"tld": "org.im", "price": 4.99, "category": 1}, {"tld": "org.in", "price": 0.99, "category": 5},
             {"tld": "org.je", "price": 24.99, "transfer": 19, "noticePeriod": 35, "category": 1},
             {"tld": "org.ki", "price": 19.99, "noticePeriod": 35, "category": 6},
             {"tld": "org.lc", "price": 8.39, "noticePeriod": 35, "category": 2},
             {"tld": "org.ls", "price": 16.79, "noticePeriod": 60, "category": 5},
             {"tld": "org.mu", "price": 14.99, "category": 4},
             {"tld": "org.my", "price": 9.99, "transfer": 86.82, "noticePeriod": 35, "category": 5,
              "details": {"localOffice": "Malaysia", "adminC": "Malaysia"}},
             {"tld": "org.nz", "price": 4.99, "category": 6},
             {"tld": "org.ph", "price": 4.99, "transfer": 35.7, "contractPeriod": 24, "noticePeriod": 35,
              "category": 5}, {"tld": "org.pl", "price": 5.99, "category": 1},
             {"tld": "org.pr", "price": 26.99, "noticePeriod": 35, "category": 2},
             {"tld": "org.ps", "price": 8.39, "transfer": 11.42, "noticePeriod": 35, "category": 5,
              "details": {"premiumDomains": True}}, {"tld": "org.pt", "price": 8.39, "noticePeriod": 60, "category": 1,
                                                     "details": {"passport": True, "vatId": True}},
             {"tld": "org.sc", "price": 12.59, "noticePeriod": 60, "authCode": True, "category": 4},
             {"tld": "org.tt", "price": 13.49, "transfer": 21.42, "contractPeriod": 36, "noticePeriod": 35,
              "authCode": True, "category": 2}, {"tld": "org.tw", "price": 4.19, "category": 5},
             {"tld": "org.uk", "price": 3.39, "transfer": 29, "contractPeriod": 24, "category": 1},
             {"tld": "org.vc", "price": 6.99, "transfer": 11.42, "noticePeriod": 35, "category": 2},
             {"tld": "org.za", "price": 2.69, "category": 4},
             {"tld": "organic", "price": 8.19, "authCode": True, "category": 8},
             {"tld": "osaka", "price": 6.69, "authCode": True, "category": 8},
             {"tld": "pa", "price": 19.995, "contractPeriod": 24, "noticePeriod": 35, "authCode": True, "category": 2},
             {"tld": "page", "price": 2.49, "authCode": True, "category": 8, "details": {"premiumDomains": True}},
             {"tld": "paris", "price": 8.39, "authCode": True, "category": 8},
             {"tld": "partners", "price": 8.39, "authCode": True, "category": 8},
             {"tld": "parts", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "party", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "pe", "price": 14.99, "transfer": 45.696, "noticePeriod": 35, "category": 3},
             {"tld": "pet", "price": 2.59, "authCode": True, "category": 8},
             {"tld": "ph", "price": 9.99, "transfer": 35.7, "contractPeriod": 24, "noticePeriod": 35, "category": 5},
             {"tld": "photo", "price": 2.99, "authCode": True, "category": 8},
             {"tld": "photography", "price": 2.99, "authCode": True, "category": 8},
             {"tld": "photos", "price": 2.99, "authCode": True, "category": 8},
             {"tld": "physio", "price": 14.99, "authCode": True, "category": 8},
             {"tld": "pics", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "pictures", "price": 1.69, "authCode": True, "category": 8},
             {"tld": "pink", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "pizza", "price": 8.49, "authCode": True, "category": 8},
             {"tld": "pk", "price": 8.39, "contractPeriod": 24, "noticePeriod": 35, "category": 5},
             {"tld": "pl", "price": 3.99, "noticePeriod": 35, "authCode": True, "category": 1},
             {"tld": "place", "price": 3.39, "authCode": True, "category": 8},
             {"tld": "plc.uk", "price": 1.69, "contractPeriod": 24, "noticePeriod": 35, "category": 1,
              "details": {"localOffice": "United Kingdom", "passport": True}},
             {"tld": "plumbing", "price": 6.69, "authCode": True, "category": 8},
             {"tld": "plus", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "pn", "price": 24.99, "transfer": 28.56, "noticePeriod": 60, "category": 6},
             {"tld": "poker", "price": 4.89, "authCode": True, "category": 8},
             {"tld": "porn", "price": 16.69, "authCode": True, "category": 8},
             {"tld": "pr", "price": 164.99, "noticePeriod": 35, "category": 2},
             {"tld": "press", "price": 8.49, "authCode": True, "category": 8},
             {"tld": "pro", "price": 2.49, "noticePeriod": 35, "authCode": True, "category": 7},
             {"tld": "pro.fj", "price": 26.49, "transfer": 113.76, "noticePeriod": 35, "category": 6},
             {"tld": "pro.pr", "price": 22.99, "noticePeriod": 35, "category": 2},
             {"tld": "productions", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "promo", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "properties", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "property", "price": 19.69, "authCode": True, "category": 8},
             {"tld": "protection", "price": 259.99, "authCode": True, "category": 8},
             {"tld": "ps", "price": 8.39, "noticePeriod": 60, "authCode": True, "category": 5,
              "details": {"premiumDomains": True}},
             {"tld": "pt", "price": 13.49, "noticePeriod": 60, "authCode": True, "category": 1,
              "details": {"passport": True}}, {"tld": "pub", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "pw", "price": 3.99, "authCode": True, "category": 6},
             {"tld": "qa", "price": 5.99, "noticePeriod": 60, "authCode": True, "category": 5},
             {"tld": "qpon", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "quebec", "price": 4.19, "authCode": True, "category": 8},
             {"tld": "racing", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "radio", "price": 37.69, "authCode": True, "category": 8},
             {"tld": "re", "price": 4.19, "authCode": True, "category": 4, "details": {"onlyEurope": True}},
             {"tld": "realestate", "price": 16.69, "authCode": True, "category": 8},
             {"tld": "realty", "price": 3.49, "authCode": True, "category": 8},
             {"tld": "recipes", "price": 5.99, "authCode": True, "category": 8},
             {"tld": "red", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "rehab", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "reise", "price": 12.19, "authCode": True, "category": 8},
             {"tld": "reisen", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "reit", "price": 144.99, "transfer": 96.8113, "authCode": True, "category": 8},
             {"tld": "rent", "price": 9.99, "authCode": True, "category": 8},
             {"tld": "rentals", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "repair", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "report", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "republican", "price": 6.99, "authCode": True, "category": 8},
             {"tld": "rest", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "restaurant", "price": 6.99, "authCode": True, "category": 8},
             {"tld": "review", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "reviews", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "rich", "price": 299.99, "authCode": True, "category": 8},
             {"tld": "rio", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "rip", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "ro", "price": 10.99, "noticePeriod": 60, "authCode": True, "category": 1,
              "details": {"passport": True, "vatId": True}},
             {"tld": "rocks", "price": 1.99, "authCode": True, "category": 8},
             {"tld": "rodeo", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "rs", "price": 20.99, "transfer": 12.852, "noticePeriod": 60, "authCode": True, "category": 1,
              "details": {"manor": "Serbia", "passport": True}},
             {"tld": "ru", "price": 4.99, "transfer": 9.9, "noticePeriod": 35, "category": 5,
              "details": {"passport": True, "vatId": True}},
             {"tld": "rugby", "price": 8.49, "authCode": True, "category": 8},
             {"tld": "rugby", "price": 8.49, "authCode": True, "category": 8},
             {"tld": "ruhr", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "run", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "ryukyu", "price": 2.59, "authCode": True, "category": 8},
             {"tld": "saarland", "price": 4.19, "authCode": True, "category": 8},
             {"tld": "sale", "price": 4.19, "authCode": True, "category": 8},
             {"tld": "salon", "price": 5.99, "authCode": True, "category": 8},
             {"tld": "sarl", "price": 4.19, "authCode": True, "category": 8},
             {"tld": "sc", "price": 11.99, "noticePeriod": 35, "authCode": True, "category": 4},
             {"tld": "school", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "school.nz", "price": 7.99, "noticePeriod": 35, "category": 6},
             {"tld": "schule", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "science", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "scot", "price": 5.99, "authCode": True, "category": 8},
             {"tld": "se", "price": 4.99, "authCode": True, "category": 1,
              "details": {"passport": True, "vatId": True, "premiumDomains": True}},
             {"tld": "security", "price": 259.99, "authCode": True, "category": 8},
             {"tld": "select", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "services", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "sex", "price": 16.79, "authCode": True, "category": 8},
             {"tld": "sexy", "price": 6.19, "authCode": True, "category": 8},
             {"tld": "sg", "price": 6.69, "authCode": True, "category": 5,
              "details": {"localOffice": "Singapore", "adminC": "Singapore", "trustee": 12.96}},
             {"tld": "sh", "price": 7.99, "authCode": True, "category": 4},
             {"tld": "shiksha", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "shoes", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "shop", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "shopping", "price": 4.89, "authCode": True, "category": 8},
             {"tld": "show", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "si", "price": 9.99, "noticePeriod": 60, "authCode": True, "category": 1},
             {"tld": "singles", "price": 4.19, "authCode": True, "category": 8},
             {"tld": "site", "price": 3.19, "authCode": True, "category": 8, "discount": {"price": 0.67,
                                                                                          "hint": "The .site-domain costs in the first year only 0,67EUR\/month. Thereafter 3,19EUR\/month."}},
             {"tld": "sk", "price": 4.19, "transfer": 27.132, "noticePeriod":
 35, "authCode": True, "category": 1,
              "details": {"onlyEurope": True, "trustee": 27.132}},
             {"tld": "ski", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "sl", "price": 8.39, "transfer": 38.556, "noticePeriod": 60, "category": 4,
              "details": {"premiumDomains": True}}, {"tld": "sn", "price": 68.99, "noticePeriod": 60, "category": 4},
             {"tld": "so", "price": 14.99, "authCode": True, "category": 4,
              "details": {"localOffice": "Somalia", "adminC": "Somalia"}},
             {"tld": "soccer", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "social", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "software", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "solar", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "solutions", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "soy", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "space", "price": 2.69, "authCode": True, "category": 8},
             {"tld": "sport", "price": 64.99, "authCode": True, "category": 8},
             {"tld": "sr", "price": 24.99, "transfer": 55.692, "noticePeriod": 60, "category": 4},
             {"tld": "srl", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "st", "price": 4.99, "noticePeriod": 35, "authCode": True, "category": 4},
             {"tld": "storage", "price": 85.69, "authCode": True, "category": 8},
             {"tld": "store", "price": 6.69, "authCode": True, "category": 8, "discount": {"price": 0.5,
                                                                                           "hint": "The .store-domain costs in the first year only 0,50EUR\/month. Thereafter 6,69EUR\/month."}},
             {"tld": "stream", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "studio", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "study", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "style", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "su", "price": 5.99, "noticePeriod": 35, "category": 5,
              "details": {"passport": True, "vatId": True}},
             {"tld": "sucks", "price": 38.99, "authCode": True, "category": 8},
             {"tld": "supplies", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "supply", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "support", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "surf", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "surgery", "price": 7.59, "authCode": True, "category": 8},
             {"tld": "swiss", "price": 14.39, "noticePeriod": 35, "authCode": True, "category": 8,
              "details": {"domainLikeCompany": True, "vatId": True, "letterOfIntent": True}},
             {"tld": "sydney", "price": 12.69, "authCode": True, "category": 8},
             {"tld": "systems", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "taipei", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "tattoo", "price": 6.19, "authCode": True, "category": 8},
             {"tld": "tax", "price": 6.79, "authCode": True, "category": 8},
             {"tld": "taxi", "price": 4.89, "authCode": True, "category": 8},
             {"tld": "tc", "price": 24.99, "transfer": 179.93, "category": 2},
             {"tld": "team", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "tech", "price": 6.69, "authCode": True, "category": 8, "discount": {"price": 0.5,
                                                                                          "hint": "The .tech-domain costs in the first year only 0,50EUR\/month. Thereafter 6,69EUR\/month."}},
             {"tld": "technology", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "tel", "price": 2.49, "authCode": True, "category": 7},
             {"tld": "tennis", "price": 5.99, "authCode": True, "category": 8},
             {"tld": "theater", "price": 4.89, "authCode": True, "category": 8},
             {"tld": "theatre", "price": 98.99, "authCode": True, "category": 8},
             {"tld": "tickets", "price": 98.99, "transfer": 65.8945, "authCode": True, "category": 8},
             {"tld": "tienda", "price": 5.99, "authCode": True, "category": 8},
             {"tld": "tips", "price": 2.69, "authCode": True, "category": 8},
             {"tld": "tires", "price": 12.99, "authCode": True, "category": 8},
             {"tld": "tirol", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "tk", "price": 1.69, "authCode": True, "category": 6},
             {"tld": "tl", "price": 12.49, "transfer": 11.42, "noticePeriod": 35, "authCode": True, "category": 5},
             {"tld": "tn", "price": 30.99, "transfer": 49, "noticePeriod": 75, "category": 4,
              "details": {"commercialRegister": "Tunisia", "localOffice": "Tunisia", "vatId": True}},
             {"tld": "tn.it", "price": 1.99, "authCode": True, "category": 1,
              "details": {"passport": True, "onlyEurope": True, "trustee": 4.92}},
             {"tld": "to", "price": 8.49, "transfer": 51.6136, "contractPeriod": 24, "noticePeriod": 35,
              "authCode": True, "category": 6}, {"tld": "today", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "tokyo", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "tools", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "top", "price": 1.69, "authCode": True, "category": 8},
             {"tld": "tours", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "town", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "toys", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "trade", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "trading", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "training", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "travel", "price": 16.69, "authCode": True, "category": 7},
             {"tld": "tt", "price": 148.99, "transfer": 29, "contractPeriod": 36, "noticePeriod": 35, "category": 2,
              "details": {"domainLimit": True, "premiumDomains": True}},
             {"tld": "tube", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "tv", "price": 4.19, "noticePeriod": 35, "authCode": True, "category": 6},
             {"tld": "tw", "price": 4.99, "noticePeriod": 35, "authCode": True, "category": 5},
             {"tld": "ua", "price": 19.99, "transfer": 51.408, "noticePeriod": 35, "category": 1},
             {"tld": "ug", "price": 9.99, "transfer": 41.412, "noticePeriod": 60, "category": 4},
             {"tld": "uk", "price": 1.69, "transfer": 29, "contractPeriod": 24, "category": 1},
             {"tld": "university", "price": 5.99, "authCode": True, "category": 8},
             {"tld": "uno", "price": 4.19, "authCode": True, "category": 8},
             {"tld": "us", "price": 2.99, "noticePeriod": 35, "authCode": True, "category": 2,
              "details": {"adminC": "United States"}},
             {"tld": "vacations", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "vc", "price": 4.19, "noticePeriod": 35, "authCode": True, "category": 2},
             {"tld": "vegas", "price": 6.69, "authCode": True, "category": 8},
             {"tld": "ventures", "price": 6.69, "authCode": True, "category": 8},
             {"tld": "versicherung", "price": 24.99, "authCode": True, "category": 8},
             {"tld": "vet", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "vg", "price": 4.99, "category": 2},
             {"tld": "viajes", "price": 7.99, "authCode": True, "category": 8},
             {"tld": "video", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "villas", "price": 7.99, "authCode": True, "category": 8},
             {"tld": "vin", "price": 6.69, "authCode": True, "category": 8},
             {"tld": "vip", "price": 2.59, "authCode": True, "category": 8},
             {"tld": "vision", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "vlaanderen", "price": 4.19, "authCode": True, "category": 8},
             {"tld": "vn", "price": 15.99, "noticePeriod": 60, "authCode": True, "category": 5,
              "details": {"passport": True}}, {"tld": "vodka", "price": 4.19, "authCode": True, "category": 8},
             {"tld": "vote", "price": 9.99, "authCode": True, "category": 8},
             {"tld": "voting", "price": 134.99, "authCode": True, "category": 8},
             {"tld": "voto", "price": 9.99, "authCode": True, "category": 8},
             {"tld": "voyage", "price": 6.69, "authCode": True, "category": 8},
             {"tld": "vu", "price": 22.49, "transfer": 22.848, "noticePeriod": 35, "category": 6},
             {"tld": "wales", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "wang", "price": 2.99, "authCode": True, "category": 8},
             {"tld": "watch", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "web.id", "price": 12.99, "transfer": 51.41, "noticePeriod": 35, "category": 5,
              "details": {"commercialRegister": "Indonesia", "localOffice": "Indonesia", "adminC": "Indonesia"}},
             {"tld": "web.za", "price": 1.99, "category": 4},
             {"tld": "webcam", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "website", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "wedding", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "whoswho", "price": 829.99, "transfer": 9959.88, "authCode": True, "category": 8},
             {"tld": "wien", "price": 4.29, "authCode": True, "category": 8, "details": {"premiumDomains": True}},
             {"tld": "wiki", "price": 3.99, "authCode": True, "category": 8},
             {"tld": "win", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "wine", "price": 7.99, "authCode": True, "category": 8},
             {"tld": "work", "price": 1.69, "authCode": True, "category": 8},
             {"tld": "works", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "world", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "ws", "price": 3.19, "authCode": True, "category": 6},
             {"tld": "wtf", "price": 4.99, "authCode": True, "category": 8},
             {"tld": "xxx", "price": 9.99, "noticePeriod": 35, "authCode": True, "category": 7},
             {"tld": "xyz", "price": 1.69, "authCode": True, "category": 8},
             {"tld": "yachts", "price": 19.99, "authCode": True, "category": 8},
             {"tld": "yoga", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "yokohama", "price": 2.49, "authCode": True, "category": 8},
             {"tld": "zone", "price": 3.19, "authCode": True, "category": 8},
             {"tld": "zuerich", "price": 11.59, "transfer": 139.08, "noticePeriod": 60, "authCode": True,
              "category": 8}, {"tld": "active", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "ads", "noticePeriod": 35, "category": 8}, {"tld": "analytics", "noticePeriod": 35, "category": 8},
             {"tld": "android", "noticePeriod": 35, "category": 8},
             {"tld": "antivirus", "noticePeriod": 35, "category": 8},
             {"tld": "arab", "noticePeriod": 35, "category": 8}, {"tld": "are", "noticePeriod": 35, "category": 8},
             {"tld": "arte", "noticePeriod": 35, "category": 8}, {"tld": "audible", "noticePeriod": 35, "category": 8},
             {"tld": "author", "noticePeriod": 35, "category": 8},
             {"tld": "autoinsurance", "noticePeriod": 35, "category": 8},
             {"tld": "banque", "noticePeriod": 35, "category": 8},
             {"tld": "baseball", "noticePeriod": 35, "category": 8}, {"tld": "bcn", "noticePeriod": 35, "category": 8},
             {"tld": "beats", "noticePeriod": 35, "category": 8}, {"tld": "boo", "noticePeriod": 35, "category": 8},
             {"tld": "book", "noticePeriod": 35, "category": 8}, {"tld": "booking", "noticePeriod": 35, "category": 8},
             {"tld": "boots", "noticePeriod": 35, "category": 8}, {"tld": "bot", "authCode": True, "category": 8},
             {"tld": "box", "noticePeriod": 35, "category": 8}, {"tld": "broadway", "noticePeriod": 35, "category": 8},
             {"tld": "budapest", "noticePeriod": 35, "category": 8}, {"tld": "buy", "noticePeriod": 35, "category": 8},
             {"tld": "cal", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "call", "noticePeriod": 35, "category": 8},
             {"tld": "cancerresearch", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "carinsurance", "noticePeriod": 35, "category": 8},
             {"tld": "cern", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "channel", "noticePeriod": 35, "category": 8}, {"tld": "circle", "category": 8},
             {"tld": "citic", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "corp", "noticePeriod": 35, "category": 8}, {"tld": "coupon", "noticePeriod": 35, "category": 8},
             {"tld": "crs", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "cruise", "noticePeriod": 35, "category": 8},
             {"tld": "cuisinella", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "dad", "noticePeriod": 35, "category": 8}, {"tld": "data", "noticePeriod": 35, "category": 8},
             {"tld": "day", "noticePeriod": 35, "category": 8}, {"tld": "deal", "noticePeriod": 35, "category": 8},
             {"tld": "dish", "noticePeriod": 35, "category": 8}, {"tld": "diy", "noticePeriod": 35, "category": 8},
             {"tld": "dnp", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "docs", "noticePeriod": 35, "category": 8}, {"tld": "doha", "noticePeriod": 35, "category": 8},
             {"tld": "dot", "noticePeriod": 35, "category": 8}, {"tld": "drive", "noticePeriod": 35, "category": 8},
             {"tld": "dubai", "noticePeriod": 35, "category": 8}, {"tld": "eat", "noticePeriod": 35, "category": 8},
             {"tld": "emerck", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "esq", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "farmers", "noticePeriod": 35, "category": 8}, {"tld": "fast", "noticePeriod": 35, "category": 8},
             {"tld": "final", "noticePeriod": 35, "category": 8},
             {"tld": "financialaid", "noticePeriod": 35, "category": 8},
             {"tld": "fire", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "fly", "noticePeriod": 35, "category": 8}, {"tld": "foo", "noticePeriod": 35, "category": 8},
             {"tld": "food", "noticePeriod": 35, "category": 8}, {"tld": "free", "noticePeriod": 35, "category": 8},
             {"tld": "frogans", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "gbiz", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "gle", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "globo", "noticePeriod": 35, "authCode": True, "category": 8}, {"tld": "gop", "category": 8},
             {"tld": "got", "noticePeriod": 35, "category": 8}, {"tld": "gree", "noticePeriod": 35, "category": 8},
             {"tld": "grocery", "noticePeriod": 35, "category": 8}, {"tld": "halal", "noticePeriod": 35, "category": 8},
             {"tld": "hangout", "noticePeriod": 35, "category": 8}, {"tld": "heart", "noticePeriod": 35, "category": 8},
             {"tld": "helsinki", "noticePeriod": 35, "category": 8}, {"tld": "here", "noticePeriod": 35, "category": 8},
             {"tld": "home", "noticePeriod": 35, "category": 8}, {"tld": "hot", "noticePeriod": 35, "category": 8},
             {"tld": "hotel", "noticePeriod": 35, "category": 8},
             {"tld": "hoteles", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "hotels", "noticePeriod": 35, "category": 8}, {"tld": "ice", "authCode": True, "category": 8},
             {"tld": "indians", "authCode": True, "category": 8}, {"tld": "ing", "authCode": True, "category": 8},
             {"tld": "ira", "noticePeriod": 35, "category": 8},
             {"tld": "islam", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "ismaili", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "jot", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "joy", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "kid", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "kids", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "kosher", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "latino", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "lds", "authCode": True, "category": 8},
             {"tld": "leclerc", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "lifeinsurance", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "lifestyle", "authCode": True, "category": 8},
             {"tld": "like", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "living", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "llp", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "mail", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "man", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "map", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "med", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "medical", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "meme", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "mls", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "mma", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "mobile", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "mormon", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "moto", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "mov", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "music", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "mutual", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "now", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "pay", "authCode": True, "category": 8},
             {"tld": "pets", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "phd", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "phone", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "play", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "post", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "prof", "noticePeriod": 35, "category": 8},
             {"tld": "read", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "realtor", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "retirement", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "roma", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "room", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "rsvp", "noticePeriod": 35, "category": 8},
             {"tld": "safe", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "save", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "scholarships", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "secure", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "shia", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "smile", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "song", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "spa", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "spot", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "talk", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "thai", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "tour", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "translations", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "travelers", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "travelersinsurance", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "trust", "noticePeriod": 35, "category": 8},
             {"tld": "tunes", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "weather", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "web", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "webs", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "wed", "authCode": True, "category": 8},
             {"tld": "winners", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "wow", "noticePeriod": 35, "category": 8},
             {"tld": "wtc", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "you", "noticePeriod": 35, "authCode": True, "category": 8},
             {"tld": "zero", "noticePeriod": 35, "category": 8},
             {"tld": "zip", "noticePeriod": 35, "authCode": True, "category": 8}]